### PR TITLE
add comment at dump-map-info

### PR DESCRIPTION
**Pull request by mqcmd196**
I add comment at dump-map-info. The `jsk_maps/raw_maps/*.yaml` files are automatically generated by `jsk_maps/src/dump-map-info.l`, however there are no explains in each files.

before
```yaml
image: eng2-7f-0.05.pgm
resolution: 0.050
origin: [-13.0, -48.5, 0]
negate: 0
occupied_thresh: 0.65
free_thresh: 0.192
map_id: /eng2/7f
```

after
```yaml
# The yaml files of jsk_maps are automatically generated at src/dump-map-info.l .
image: eng2-7f-0.05.pgm
resolution: 0.050
origin: [-13.0, -48.5, 0]
negate: 0
occupied_thresh: 0.65
free_thresh: 0.192
map_id: /eng2/7f
```

### CODE REVIEW

**Comment by mqcmd196** [comment]
@708yamaguchi

**Comment by 708yamaguchi** [comment]
Nice!

I think this comment makes it easier for users to understand `jsk_maps` system.

**Comment by knorth55** [comment]
@mqcmd196 can you resolve the conflict?

**Comment by mqcmd196** [comment]
I resolved it. Waiting for CI...

**Pull request merged**
