### PR TITLE
[drc_task_common] Add trajectory.l to interpolate trajectory linearly

### PR DESCRIPTION
**Pull request by garaemon**
door-trajectory

### CODE REVIEW

**Comment by snozawa** [comment]
Is `euslib/rbrain/virtual_interpolator.l`  used for this case?
```
(progn                                                                                                                                                                                                                                                                    
(load "~/prog/euslib/rbrain/virtual_interpolator.l")                                                                                                                                                                                                                                  
(load "~/prog/euslib/jsk/gnuplotlib.l")                                                                                                                                                                                                                                               
(graph-view (list (mapcar #'(lambda (x) (elt x 0)) (cadr (memq :data (pos-list-interpolation (list #f(0) #f(90) #F(-90)) (list 2 2) 0.01 :interpolator-class linear-interpolator)))))))
```

`virtual_interpolator.l` is old code, but you can change interpolation method.

**Comment by garaemon** [comment]
@snozawa It just uses `midcoords`

The class provides via-coords according to the number of resolution based on several via coords.

**Comment by snozawa** [comment]
I see.

**Comment by garaemon** [comment]
N=12 (minimum)

screenshot from 2015-12-14 17 54 26


N=24

screenshot from 2015-12-14 17 54 40

**Comment by garaemon** [comment]
cannot install jsk_pcl_ros

http://jenkins.ros.org/view/IbinS32/job/ros-indigo-jsk-pcl-ros_binarydeb_saucy_i386/

**Comment by k-okada** [comment]
```

-- Installing: /tmp/buildd/ros-indigo-jsk-pcl-ros-0.3.8-1trusty-20151213-0606/debian/ros-indigo-jsk-pcl-ros/opt/ros/indigo/include/jsk_pcl_ros/PolygonArrayAreaLikelihoodConfig.h
CMake Error at cmake_install.cmake:67 (FILE):
  file INSTALL cannot find
  "/tmp/buildd/ros-indigo-jsk-pcl-ros-0.3.8-1trusty-20151213-0606/obj-x86_64-linux-gnu/devel/include/jsk_pcl_ros/cuboid_parameterConfig.h".


make[2]: *** [install] Error 1

```


--
◉ Kei Okada

**Pull request closed without merging**
