### PR TITLE
[detect_cans] async join based parallel state-machine

### PR DESCRIPTION
**Pull request by h-kamada**
#### async-join-based-structure-hazard-check-state-machine

* When you want to execute an action, async-join-based-structure-hazard-check-state-machine manages this action by managing 3 states (check, join, and exec state).

##### check state
* checks whether or not executing action is possible by considering structure hazard. If possible, transitions to exec state. If not possible, transitions to join state

##### join state
* wait until the actions ends

##### exec state
* execute the action.

### CODE REVIEW

**Comment by k-okada** [comment]
ok, lets check this on real robot,  11:00 tomorrow. I'm visiting room 73b2
as psudo VIP

--
◉ Kei Okada

**Comment by h-kamada** [comment]
I have to take a class tommorow. Please check on Thursday.

**Comment by k-okada** [comment]
when can i see your demo, 15:00 today?

**Comment by h-kamada** [comment]
Yes, please check!

**Comment by h-kamada** [comment]
this version uses https://github.com/jsk-ros-pkg/jsk_demos/pull/1107/files#diff-fd53bdf61f10fba27d278de10ebe8079, but runs each action sequentially,

Next step is to run them in parallel

**Comment by h-kamada** [comment]
Confirmed on real robot!

**Comment by h-kamada** [comment]
please merge @k-okada

**Pull request merged**
