### PR TITLE
[jsk_demo_common/euslisp/pr2-action.l] fix: add '_lk' to link name

### PR DESCRIPTION
**Pull request by furushchev**
fix for change of calling link name directly in pr2-interface

### CODE REVIEW

**Comment by furushchev** [comment]
> Your test run exceeded 50 minutes. 

please restart travis

**Comment by k-okada** [comment]
from discussion -> https://github.com/jsk-ros-pkg/jsk_model_tools/issues/18
we're encouraged  to use `:link "name"` ?? (i think @snozawa is the expert on this issue)

**Comment by furushchev** [comment]
@k-okada OK I fixed.

**Comment by snozawa** [comment]
Sorry for late reply.
Robot model `.l` from `euscollada` conversion has fast accessing method for joints and links.
Previously, the naming of these accessing methods are same as joint names and link names.
However, for some robots, joint name and link name are same and methods names conflicts.
So, @YoheiKakiuchi employ the naming like `xx_lk` for link accessing methods.

https://github.com/euslisp/jskeus/blob/master/irteus/test/robot-model-usage.l
is the unittest for robot properties accessors.

Recommended accessors are:
- `(send *robot* :link "torso_lift_link")` : It can be robot independent codes because we can generalize `"torso_lift_link"` as robot's link name. But slow.
- `(send *robot* :torso_lift_link_lk)` : Robot specific description and hard to re-use for other robots, but fast (because of no `find` processing).

**Pull request merged**
