### PR TITLE
[jsk_maps] improve jsk maps

### PR DESCRIPTION
**Pull request by furushchev**
- use ros path for generated launch files
- added option `launch_map_server` for generated launch files
- use `xml` extension for generated launch files not to be launched by `roslaunch` directly
- cleaned up codes
- added README

### CODE REVIEW

**Comment by furushchev** [comment]
waiting for https://github.com/jsk-ros-pkg/jsk_planning/pull/56

**Comment by furushchev** [comment]
waiting for https://github.com/jsk-ros-pkg/jsk_planning/pull/60

**Comment by furushchev** [comment]
Yay! Test passed.
@k-okada Please review and merge if there is no problem.

**Comment by furushchev** [comment]
@k-okada Thanks a lot!

**Comment by furushchev** [comment]
@k-okada Please also release this package when you have time.

**Comment by furushchev** [comment]
@k-okada Could you release this package?

**Comment by k-okada** [comment]
sorry for late, done https://github.com/ros/rosdistro/pull/14174

--
◉ Kei Okada


2017-03-13 18:47 GMT+09:00 Furushchev <notifications@github.com>:

**Comment by furushchev** [comment]
@k-okada Thank you very much!

**Pull request merged**
