### PR TITLE
Fix open hand in hrp2jsk

### PR DESCRIPTION
**Pull request by orikuma**

### CODE REVIEW

**Comment by garaemon** [comment]
```
]2;[build] 18/24[jsk_demo_common] CMake Error: Attempt to add a custom rule to output "/home/travis/ros/ws_jsk_demos/devel/share/roseus/ros/jsk_demo_common/manifest.l.rule" which already has a custom rule. 
]2;[build] 18/24[jsk_demo_common] CMake Error at /home/travis/ros/ws_jsk_demos/build/jsk_demo_common/cmake/jsk_demo_common-genmsg.cmake:137 (add_custom_target): 
]2;[build] 18/24[jsk_demo_common]   add_custom_target cannot create target                      
]2;[build] 18/24[jsk_demo_common]   "jsk_demo_common_generate_messages_eus" because another target with the 
]2;[build] 18/24[jsk_demo_common]   same name already exists.  The existing target is a custom target created 
]2;[build] 18/24[jsk_demo_common]   in source directory                                         
]2;[build] 18/24[jsk_demo_common]   "/home/travis/ros/ws_jsk_demos/src/jsk_demos/jsk_demo_common".  See 
]2;[build] 18/24[jsk_demo_common]   documentation for policy CMP0002 for more details.          
]2;[build] 18/24[jsk_demo_common] Call Stack (most recent call first):                          
]2;[build] 18/24[jsk_demo_common]   /opt/ros/hydro/share/genmsg/cmake/genmsg-extras.cmake:299 (include) 
]2;[build] 18/24[jsk_demo_common]   catkin.cmake:25 (generate_messages)                         
]2;[build] 18/24[jsk_demo_common]   CMakeLists.txt:2 (include)                                  
]2;[build] 18/24[jsk_demo_common]                                                               
]2;[build] 18/24[jsk_demo_common]                                                               
```

**Comment by k-okada** [comment]
this should be solved in https://github.com/jsk-ros-pkg/jsk_roseus/pull/286

--
◉ Kei Okada

**Comment by garaemon** [comment]
Latest geneus should solve this

**Comment by k-okada** [comment]
this is not geneus, but roseus/cmake/roseus.cmake problem

--
◉ Kei Okada

**Comment by garaemon** [comment]
Please release new version of roseus

**Comment by k-okada** [comment]
yes, waiting for
https://travis-ci.org/jsk-ros-pkg/jsk_roseus/builds/60080607

--
◉ Kei Okada

**Pull request merged**
