### PR TITLE
DO NOT MERGE YET

### PR DESCRIPTION
**Pull request by h-kamada**
##### divide fridge demo function to exec parallel
At present, 2 function is being divided.
* goto-front-of-fridge (finished)
* open-fridge-door  (yet)

### CODE REVIEW

**Comment by h-kamada** [comment]
All function is divided.
But , this code is not executed in real yet.
So, I'll execute it and if everything worked well, please merge.

**Comment by furushchev** [comment]
did you check on real robot?

**Comment by h-kamada** [comment]
checked in real robot.
But, still some points should be solved .
For example, 

In case PR2 is going to open the fridge door but failed to catch the fridge door, 
previous version can redo because those motions are in dotimes loop.
But , in the new one, the motions are written sequentially. So PR2 can't revenge. 
This situation will be managed in state-machine in the future.

**Comment by k-okada** [comment]
If original code is
(defun a nil
   (dotimes (i 3)
      xxxx
      ))

Then please write as
dotimes (i 3)
   (b)

The first version is just to split a big function to small functions and do
not change and behavior

Send version is to introduce smach and not to change behavior as much as
possible

2015年7月24日金曜日、h-kamada<notifications@github.com>さんは書きました:

> checked in real robot.
> But, still some points should be solved .
> For example,
>
> In case PR2 is going to open the fridge door but failed to catch the
> fridge door,
> previous version can redo because those motions are in dotimes loop.
> But , in the new one, the motions are written sequentially. So PR2 can't
> revenge.
> This situation will be managed in state-machine in the future.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_demos/pull/995#issuecomment-124487292>
> .
>


-- 
--
◉ Kei Okada

**Comment by h-kamada** [comment]
OK !
I'll do it.
After spliting to small functions, next step is to manage state in state-machine or smach.
Is it ok?

**Comment by garaemon** [comment]
> After spliting to small functions, next step is to manage state in state-machine or smach.

I think you need more smaller goals which are reachable in one day.
For example, using mask in perception program.

**Comment by h-kamada** [comment]
I see. Thank you,

**Comment by h-kamada** [comment]
> If original code is (defun a nil (dotimes (i 3) xxxx )) Then please write as dotimes (i 3) (b)

I changed code to this version.
Please merge.

**Comment by k-okada** [comment]
did you confirm if this works on real robot?

--
◉ Kei Okada

**Comment by h-kamada** [comment]
Yes, checked in real robot.

**Comment by k-okada** [comment]
Great! so please update jsk_demos in application user on the real robot and confirm again .

**Pull request merged**
