### PR TITLE
Update welcome_to_jsk_fetch

### PR DESCRIPTION
**Pull request by 708yamaguchi**
We updated `welcome_to_jsk_fetch` code and used today's demo.

Here is the video created from `/head_camera/rgb/throttled/image_rect_color/compressed` and `/audio` (Available only for JSK users)
video https://drive.google.com/file/d/1hWtJelZSXNUAzr0WlS6guk-wElcx2EQW/view?usp=sharing
rosbag https://drive.google.com/file/d/1XbznvfQpdVflDpEPe3rr67IvhO4M5SMB/view?usp=sharing

Thank you very much for your help @iory

### CODE REVIEW

**Comment by k-okada** [comment]
nice, can we add this demo to apps?

**Comment by 708yamaguchi** [comment]
I added this demo to jsk_fetch_startup app.
https://github.com/jsk-ros-pkg/jsk_robot/pull/1502

In addition, fetch sends email about the demo.
Please see
```
Welcome to JSK demo: 2022/06/07 (17:11:51)
```

**Comment by tkmtnt7000** [comment]
音声コマンドからこのデモを起動できるようにしました．
https://drive.google.com/file/d/1v4zLyKEEkKizb-J49LMTMQQS7YOYxHkz/view?usp=sharing
(動画中ではFetch15で実験していたため途中ジョイスティックでアシストしています．．．)

**Comment by 708yamaguchi** [comment]
See mail
Welcome to JSK demo: 2022/06/07 (22:13:31)

**Comment by mqcmd196** [comment]
@k-okada @708yamaguchi 
If the application is registered at Dialogflow and app_manager, we can use from Google Chat automatically. This is depends on `jsk_fetch_startup/launch/fetch_bringup`. I'll send the PR about it.

**Pull request merged**
