### PR TITLE
[jsk_maps] add keepout map for eng2/eng6/eng8 and update eng2 maps

### PR DESCRIPTION
**Pull request by knorth55**
add eng2/eng6/eng8 building keepout maps and update eng2 maps

- update eng2/1f, eng2/2f, eng2/3f and eng2/7f
- add keepout map for eng2, eng6 and eng8
- add xcf file for gimp edit
- generate keepout.yaml in `catkin build`
- add `keepout` argument in `launch/include/start_map_eng2/eng6/emg8.xml`
- add `keepout` argument in `launch/start_map_eng2/eng8.launch`

### Eng2 1F
eng2-1f-0 05

### Eng2 1F Keepout

eng2-1f-0 05_keepout

### Eng2 2F

eng2-2f-0 05

### Eng2 2F Keepout

eng2-2f-0 05_keepout

### Eng2 3F

eng2-3f-0 05

### Eng2 3F Keepout

eng2-3f-0 05_keepout

### Eng2 7F

Update(2020/08/06): add vending machine
Update(2020/08/07): update 73B2 map #1284 
Update(2020/11/13): update 73B2 kitchen map https://github.com/knorth55/jsk_demos/pull/7

eng2-7f-0 05

### Eng2 7F Keepout

Update(2020/08/06): add vending machine
Update(2020/08/07): update 73B2 map #1284 
Update(2020/11/13): update 73B2 kitchen map https://github.com/knorth55/jsk_demos/pull/7

eng2-7f-0 05_keepout

### Eng2 8F Keepout

eng2-8f-0 05_keepout

### Eng6 B1F Keepout

eng6-b1f-0 05_keepout

### Eng6 1F Keepout

eng6-1f-0 05_keepout

### Eng6 2F Keepout

eng6-2f-0 05_keepout

### Eng6 3F Keepout

eng6-3f-0 05_keepout

### Eng6 4F Keepout

eng6-4f-0 05_keepout

### Eng8 B1F Keepout

eng8-b1f-0 05_keepout

### Eng8 1F Keepout

eng8-1f-0 05_keepout

### Eng8 6F Keepout

eng8-6f-0 05_keepout

cc. @708yamaguchi

### CODE REVIEW

**Comment by knorth55** [comment]
@708yamaguchi can you check these maps?

**Comment by knorth55** [comment]
generated `launch/include/start_map_eng2_main.xml` launch

```xml
<launch>
  <arg name="keepout" default="true"/>
  <arg name="launch_map_server" default="true"/>

  <group if="$(arg launch_map_server)">
    <!-- map for visualization nodes -->
    <group if="$(arg keepout)">
      <node name="$(anon map_server00)" pkg="map_server" type="map_server"
            args="$(find jsk_maps)/raw_maps/eng2-7f-0.05_keepout.yaml" >
        <remap from="map" to="/eng2/7f"/>
        <param name="frame_id" value="/eng2/7f"/>
      </node>
      <node name="$(anon map_server01)" pkg="map_server" type="map_server"
            args="$(find jsk_maps)/raw_maps/eng2-1f-0.05_keepout.yaml" >
        <remap from="map" to="/eng2/1f"/>
        <param name="frame_id" value="/eng2/1f"/>
      </node>
      <node name="$(anon map_server02)" pkg="map_server" type="map_server"
            args="$(find jsk_maps)/raw_maps/eng2-2f-0.05_keepout.yaml" >
        <remap from="map" to="/eng2/2f"/>
        <param name="frame_id" value="/eng2/2f"/>
      </node>
      <node name="$(anon map_server03)" pkg="map_server" type="map_server"
            args="$(find jsk_maps)/raw_maps/eng2-3f-0.05_keepout.yaml" >
        <remap from="map" to="/eng2/3f"/>
        <param name="frame_id" value="/eng2/3f"/>
      </node>
      <node name="$(anon map_server04)" pkg="map_server" type="map_server"
            args="$(find jsk_maps)/raw_maps/eng2-8f-0.05_keepout.yaml" >
        <remap from="map" to="/eng2/8f"/>
        <param name="frame_id" value="/eng2/8f"/>
      </node>
    </group>
    <group unless="$(arg keepout)">
      <node name="$(anon map_server00)" pkg="map_server" type="map_server"
            args="$(find jsk_maps)/raw_maps/eng2-7f-0.05.yaml" >
        <remap from="map" to="/eng2/7f"/>
        <param name="frame_id" value="/eng2/7f"/>
      </node>
      <node name="$(anon map_server01)" pkg="map_server" type="map_server"
            args="$(find jsk_maps)/raw_maps/eng2-1f-0.05.yaml" >
        <remap from="map" to="/eng2/1f"/>
        <param name="frame_id" value="/eng2/1f"/>
      </node>
      <node name="$(anon map_server02)" pkg="map_server" type="map_server"
            args="$(find jsk_maps)/raw_maps/eng2-2f-0.05.yaml" >
        <remap from="map" to="/eng2/2f"/>
        <param name="frame_id" value="/eng2/2f"/>
      </node>
      <node name="$(anon map_server03)" pkg="map_server" type="map_server"
            args="$(find jsk_maps)/raw_maps/eng2-3f-0.05.yaml" >
        <remap from="map" to="/eng2/3f"/>
        <param name="frame_id" value="/eng2/3f"/>
      </node>
      <node name="$(anon map_server04)" pkg="map_server" type="map_server"
            args="$(find jsk_maps)/raw_maps/eng2-8f-0.05.yaml" >
        <remap from="map" to="/eng2/8f"/>
        <param name="frame_id" value="/eng2/8f"/>
      </node>
    </group>

    <!-- map for navigation nodes -->
    <node name="map_server" pkg="multi_map_server" type="multi_map_server"
          if="$(arg keepout)" args="$(find jsk_maps)/raw_maps/eng2-7f-0.05_keepout.yaml
          $(find jsk_maps)/raw_maps/eng2-1f-0.05_keepout.yaml
          $(find jsk_maps)/raw_maps/eng2-2f-0.05_keepout.yaml
          $(find jsk_maps)/raw_maps/eng2-3f-0.05_keepout.yaml
          $(find jsk_maps)/raw_maps/eng2-8f-0.05_keepout.yaml
    " />
    <node name="map_server" pkg="multi_map_server" type="multi_map_server"
          unless="$(arg keepout)" args="$(find jsk_maps)/raw_maps/eng2-7f-0.05.yaml
          $(find jsk_maps)/raw_maps/eng2-1f-0.05.yaml
          $(find jsk_maps)/raw_maps/eng2-2f-0.05.yaml
          $(find jsk_maps)/raw_maps/eng2-3f-0.05.yaml
          $(find jsk_maps)/raw_maps/eng2-8f-0.05.yaml
    " />
  </group>

  <node pkg="tf" type="static_transform_publisher" name="$(anon map_tf00)"
        args="  0.000   0.000  30.000 0 0 0 /eng2 /eng2/7f 100"/>
  <node pkg="tf" type="static_transform_publisher" name="$(anon map_tf01)"
        args="  0.000   0.000   0.000 0 0 0 /eng2/7f /map 100" >
    <remap from="tf" to="/eng2/7f_tf"/>
  </node>
  <node pkg="tf" type="static_transform_publisher" name="$(anon map_tf02)"
        args="  0.000   0.000   0.000 0 0 0 /eng2 /eng2/1f 100"/>
  <node pkg="tf" type="static_transform_publisher" name="$(anon map_tf03)"
        args="  0.000   0.000   0.000 0 0 0 /eng2/1f /map 100" >
    <remap from="tf" to="/eng2/1f_tf"/>
  </node>
  <node pkg="tf" type="static_transform_publisher" name="$(anon map_tf04)"
        args="  0.000   0.000  10.000 0 0 0 /eng2 /eng2/2f 100"/>
  <node pkg="tf" type="static_transform_publisher" name="$(anon map_tf05)"
        args="  0.000   0.000   0.000 0 0 0 /eng2/2f /map 100" >
    <remap from="tf" to="/eng2/2f_tf"/>
  </node>
  <node pkg="tf" type="static_transform_publisher" name="$(anon map_tf06)"
        args="  0.000   0.000  20.000 0 0 0 /eng2 /eng2/3f 100"/>
  <node pkg="tf" type="static_transform_publisher" name="$(anon map_tf07)"
        args="  0.000   0.000   0.000 0 0 0 /eng2/3f /map 100" >
    <remap from="tf" to="/eng2/3f_tf"/>
  </node>
  <node pkg="tf" type="static_transform_publisher" name="$(anon map_tf08)"
        args="  0.000   0.000  40.000 0 0 0 /eng2 /eng2/8f 100"/>
  <node pkg="tf" type="static_transform_publisher" name="$(anon map_tf09)"
        args="  0.000   0.000   0.000 0 0 0 /eng2/8f /map 100" >
    <remap from="tf" to="/eng2/8f_tf"/>
  </node>
  <node name="tf_mux" pkg="topic_tools" type="mux"
        args="tf  /eng2/7f_tf /eng2/1f_tf /eng2/2f_tf /eng2/3f_tf /eng2/8f_tf">
    <remap from="mux" to="map_tf_mux" />
  </node>
</launch>
```

**Comment by 708yamaguchi** [comment]
I think `keepout` arg is nice feature.

My concern is that the keepout area (black area) is added at entrance.
For example, upper left black area in Eng2 1F Keepout is the entrance at which fetch or PR2 can go out.
I think such entrance area should not be marked as keepout.

**Comment by knorth55** [comment]
@708yamaguchi your concern is right, but we should mark there as keepout now.
When @YutoUchimi and I tried to go to subway without keepout mark, PR2 finds a path to go out from building and come into another entrance.
We marked entrance as keepout to prevent that kind of path.

But maybe, for the 1st and 2nd floor, we only have one valid entrance for each floor, so we can remove that keepout mark.

**Comment by knorth55** [comment]
@708yamaguchi I updated to remove keepout in the entrance in 1f/2f

**Comment by knorth55** [comment]
I update to add keepout maps for eng6 and eng8 building.

**Comment by knorth55** [comment]
I update to separately use `/map` and `/map_keepout`.
`/map` is for `amcl` and `/map_keepout` is for `/move_base`.

**Comment by knorth55** [comment]
@mqcmd196 thank you for your update. I cherry-picked your update of eng2 3f map to this PR.

**Comment by knorth55** [comment]
@mqcmd196 Thank you for your update. I cheery-picked your commit in https://github.com/knorth55/jsk_demos/pull/5

**Comment by knorth55** [comment]
@Kanazawanaoaki @mqcmd196 
Fetch15 and PR1040 is now using this map inside, so please be careful.

@k-okada 
can you please merge this PR?
this PR adds keepout for all floors and @mqcmd196 is now updating it for Fetch and Spot.
@Kanazawanaoaki is also changing this map for kitchen experiments.

**Comment by knorth55** [comment]
@Kanazawanaoaki thank you for updating the map. I will update map inside pr1040 and fetch15.

**Review by k-okada — APPROVED** [review]
nice!

**Comment by knorth55** [comment]
@k-okada travis passed! can you please merge this PR?

**Pull request merged**
