### PR TITLE
Icp Update drill recognition parameter around ICP

### PR DESCRIPTION
**Pull request by garaemon**

### CODE REVIEW

**Comment by garaemon** [comment]
We found that point-to-point is better than point-to-plane on this configuration. probably normal is not so good...?

**Comment by garaemon** [comment]
This includes https://github.com/jsk-ros-pkg/jsk_demos/pull/274 and https://github.com/jsk-ros-pkg/jsk_demos/pull/278

**Comment by garaemon** [comment]
roslint required again

```
-- run_tests.py: execute commands
  /opt/ros/hydro/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/travis/ros/ws_jsk_demos/src/jsk_demos/elevator_move_base_pr2 --package=elevator_move_base_pr2 --results-filename test_test-color-point-detector.xml /home/travis/ros/ws_jsk_demos/src/jsk_demos/elevator_move_base_pr2/test/test-color-point-detector.launch 
... logging to /home/travis/.ros/log/rostest-testing-worker-linux-e7a62211-1-21232-linux-1-52168733-15406.log
[ROSUNIT] Outputting test results to /home/travis/ros/ws_jsk_demos/build/elevator_move_base_pr2/test_results/elevator_move_base_pr2/rostest-test_test-color-point-detector.xml
Traceback (most recent call last):
  File "/home/travis/ros/ws_jsk_demos/src/jsk_demos/elevator_move_base_pr2/test/test-color-point-detector.py", line 3, in <module>
    import roslib; roslib.load_manifest(PKG)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/roslib/launcher.py", line 62, in load_manifest
    sys.path = _generate_python_path(package_name, _rospack) + sys.path
  File "/opt/ros/hydro/lib/python2.7/dist-packages/roslib/launcher.py", line 98, in _generate_python_path
    packages = get_depends(pkg, rospack) 
  File "/opt/ros/hydro/lib/python2.7/dist-packages/roslib/launcher.py", line 51, in get_depends
    vals = rospack.get_depends(package, implicit=True)
  File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 236, in get_depends
    s.update(self.get_depends(p, implicit))
  File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 236, in get_depends
    s.update(self.get_depends(p, implicit))
  File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 236, in get_depends
    s.update(self.get_depends(p, implicit))
  File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 236, in get_depends
    s.update(self.get_depends(p, implicit))
  File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 230, in get_depends
    names = [p.name for p in self.get_manifest(name).depends]
  File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 163, in get_manifest
    return self._load_manifest(name)
  File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 207, in _load_manifest
    retval = self._manifests[name] = parse_manifest_file(self.get_path(name), self._manifest_name, rospack=self)
  File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 199, in get_path
    raise ResourceNotFound(name, ros_paths=self._ros_paths)
rospkg.common.ResourceNotFound: roslint
```

**Comment by garaemon** [comment]
xacro depends on roslint but ros-hydro-xacro does not require roslint.
`rosdep install xacro` can install ros-hydro-roslint

**Comment by k-okada** [comment]
/opt/ros/hydro/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/travis/ros/ws_jsk_demos/src/jsk_demos/elevator_move_base_pr2 --package=elevator_move_base_pr2 --results-filename test_test-color-point-detector.xml /home/travis/ros/ws_jsk_demos/src/jsk_demos/elevator_move_base_pr2/test/test-color-point-detector.launch 
... logging to /home/travis/.ros/log/rostest-testing-worker-linux-968a87ce-2-8546-linux-17-52168732-917.log
[ROSUNIT] Outputting test results to /home/travis/ros/ws_jsk_demos/build/elevator_move_base_pr2/test_results/elevator_move_base_pr2/rostest-test_test-color-point-detector.xml
Traceback (most recent call last):
  File "/home/travis/ros/ws_jsk_demos/src/jsk_demos/elevator_move_base_pr2/test/test-color-point-detector.py", line 3, in <module>
    import roslib; roslib.load_manifest(PKG)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/roslib/launcher.py", line 62, in load_manifest
    sys.path = _generate_python_path(package_name, _rospack) + sys.path
  File "/opt/ros/hydro/lib/python2.7/dist-packages/roslib/launcher.py", line 98, in _generate_python_path
    packages = get_depends(pkg, rospack) 
  File "/opt/ros/hydro/lib/python2.7/dist-packages/roslib/launcher.py", line 51, in get_depends
    vals = rospack.get_depends(package, implicit=True)
  File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 236, in get_depends
    s.update(self.get_depends(p, implicit))
  File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 236, in get_depends
    s.update(self.get_depends(p, implicit))
  File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 236, in get_depends
    s.update(self.get_depends(p, implicit))
  File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 236, in get_depends
    s.update(self.get_depends(p, implicit))
  File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 230, in get_depends
    names = [p.name for p in self.get_manifest(name).depends]
  File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 163, in get_manifest
    return self._load_manifest(name)
  File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 207, in _load_manifest
    retval = self._manifests[name] = parse_manifest_file(self.get_path(name), self._manifest_name, rospack=self)
  File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 199, in get_path
    raise ResourceNotFound(name, ros_paths=self._ros_paths)
rospkg.common.ResourceNotFound: roslint
ROS path [0]=/opt/ros/hydro/share/ros
ROS path [1]=/home/travis/ros/ws_jsk_demos/src/jsk_demos/jsk_2015_06_hrp_drc/drc_com_common

**Pull request merged**
