### PR TITLE
Add action server sample launch

### PR DESCRIPTION
**Pull request by furushchev**

### CODE REVIEW

**Comment by k-okada** [comment]
missing `add_rostest`, you have to add `find_package(rostest)`

```
]2;[build] 18/23]2;[build] 18/23[jsk_demo_common] -- Generating .msg files for action jsk_demo_common/PR2Common /home/travis/ros/ws_jsk_demos/src/jsk_demos/jsk_demo_common/action/PR2Common.action 
]2;[build] 18/23[jsk_demo_common] Generating for action PR2Common                               
]2;[build] 18/23]2;[build] 18/23]2;[build] 18/23]2;[build] 18/23]2;[build] 18/23[jsk_demo_common] -- jsk_demo_common: 7 messages, 0 services                    
]2;[build] 18/23]2;[build] 18/23]2;[build] 18/23]2;[build] 18/23[jsk_demo_common] CMake Error at CMakeLists.txt:53 (add_rostest):               
]2;[build] 18/23[jsk_demo_common]   Unknown CMake command "add_rostest".                        
]2;[build] 18/23[jsk_demo_common]
```

**Comment by garaemon** [comment]
```
eustf roseus_c_util roseus_c_util [ERROR] [1430286641.494555291]: Could not find roseus messages for audio_common_msgs under (/home/travis/ros/ws_jsk_demos/devel/share/roseus/ros /opt/ros/hydro/share/roseus/ros)
try rosrun roseus generate-all-msg-srv.sh audio_common_msgs
[ERROR] [1430286641.494635903]: Could not find roseus messages for audio_common_msgs under (/home/travis/ros/ws_jsk_demos/devel/share/roseus/ros /opt/ros/hydro/share/roseus/ros)
try rosrun roseus generate-all-msg-srv.sh audio_common_msgs
[ERROR] [1430286641.501584842]: Could not find roseus messages for diagnostic_msgs under (/home/travis/ros/ws_jsk_demos/devel/share/roseus/ros /opt/ros/hydro/share/roseus/ros)
try rosrun roseus generate-all-msg-srv.sh diagnostic_msgs
[ERROR] [1430286641.501655939]: Could not find roseus messages for diagnostic_msgs under (/home/travis/ros/ws_jsk_demos/devel/share/roseus/ros /opt/ros/hydro/share/roseus/ros)
try rosrun roseus generate-all-msg-srv.sh diagnostic_msgs
[ERROR] [1430286641.680820940]: Could not find roseus messages for driver_base under (/home/travis/ros/ws_jsk_demos/devel/share/roseus/ros /opt/ros/hydro/share/roseus/ros)
try rosrun roseus generate-all-msg-srv.sh driver_base
[ERROR] [1430286641.680898773]: Could not find roseus messages for driver_base under (/home/travis/ros/ws_jsk_demos/devel/share/roseus/ros /opt/ros/hydro/share/roseus/ros)
try rosrun roseus generate-all-msg-srv.sh driver_base
[ERROR] [1430286641.722790918]: Could not find roseus messages for pddl_msgs under (/home/travis/ros/ws_jsk_demos/devel/share/roseus/ros /opt/ros/hydro/share/roseus/ros)
try rosrun roseus generate-all-msg-srv.sh pddl_msgs
[ERROR] [1430286641.722879864]: Could not find roseus messages for pddl_msgs under (/home/travis/ros/ws_jsk_demos/devel/share/roseus/ros /opt/ros/hydro/share/roseus/ros)
try rosrun roseus generate-all-msg-srv.sh pddl_msgs
[ERROR] [1430286641.857231611]: Could not find roseus messages for posedetection_msgs under (/home/travis/ros/ws_jsk_demos/devel/share/roseus/ros /opt/ros/hydro/share/roseus/ros)
try rosrun roseus generate-all-msg-srv.sh posedetection_msgs
[ERROR] [1430286641.857327374]: Could not find roseus messages for posedetection_msgs under (/home/travis/ros/ws_jsk_demos/devel/share/roseus/ros /opt/ros/hydro/share/roseus/ros)
try rosrun roseus generate-all-msg-srv.sh posedetection_msgs
[ERROR] [1430286641.870784634]: Could not find roseus messages for smach_msgs under (/home/travis/ros/ws_jsk_demos/devel/share/roseus/ros /opt/ros/hydro/share/roseus/ros)
try rosrun roseus generate-all-msg-srv.sh smach_msgs
[ERROR] [1430286641.870872423]: Could not find roseus messages for smach_msgs under (/home/travis/ros/ws_jsk_demos/devel/share/roseus/ros /opt/ros/hydro/share/roseus/ros)
try rosrun roseus generate-all-msg-srv.sh smach_msgs
[ERROR] [1430286647.776121405]: Could not find roseus messages for audio_common_msgs under (/home/travis/ros/ws_jsk_demos/devel/share/roseus/ros /opt/ros/hydro/share/roseus/ros)
try rosrun roseus generate-all-msg-srv.sh audio_common_msgs
[ERROR] [1430286647.776230129]: Could not find roseus messages for audio_common_msgs under (/home/travis/ros/ws_jsk_demos/devel/share/roseus/ros /opt/ros/hydro/share/roseus/ros)
try rosrun roseus generate-all-msg-srv.sh audio_common_msgs
[ERROR] [1430286647.777843927]: Could not find roseus messages for diagnostic_msgs under (/home/travis/ros/ws_jsk_demos/devel/share/roseus/ros /opt/ros/hydro/share/roseus/ros)
try rosrun roseus generate-all-msg-srv.sh diagnostic_msgs
[ERROR] [1430286647.777906460]: Could not find roseus messages for diagnostic_msgs under (/home/travis/ros/ws_jsk_demos/devel/share/roseus/ros /opt/ros/hydro/share/roseus/ros)
try rosrun roseus generate-all-msg-srv.sh diagnostic_msgs
[ERROR] [1430286648.008730475]: Could not find roseus messages for audio_common_msgs under (/home/travis/ros/ws_jsk_demos/devel/share/roseus/ros /opt/ros/hydro/share/roseus/ros)
try rosrun roseus generate-all-msg-srv.sh audio_common_msgs
[ERROR] [1430286648.008836565]: Could not find roseus messages for audio_common_msgs under (/home/travis/ros/ws_jsk_demos/devel/share/roseus/ros /opt/ros/hydro/share/roseus/ros)
try rosrun roseus generate-all-msg-srv.sh audio_common_msgs
[ERROR] [1430286648.010512590]: Could not find roseus messages for diagnostic_msgs under (/home/travis/ros/ws_jsk_demos/devel/share/roseus/ros /opt/ros/hydro/share/roseus/ros)
try rosrun roseus generate-all-msg-srv.sh diagnostic_msgs
[ERROR] [1430286648.010585352]: Could not find roseus messages for diagnostic_msgs under (/home/travis/ros/ws_jsk_demos/devel/share/roseus/ros /opt/ros/hydro/share/roseus/ros)
try rosrun roseus generate-all-msg-srv.sh diagnostic_msgs
[ERROR] [1430286648.120417594]: Could not find roseus messages for posedetection_msgs under (/home/travis/ros/ws_jsk_demos/devel/share/roseus/ros /opt/ros/hydro/share/roseus/ros)
try rosrun roseus generate-all-msg-srv.sh posedetection_msgs
[ERROR] [1430286648.120457523]: Could not find nil/manifest.l
try rosrun roseus generate-all-msg-srv.sh posedetection_msgs
[ERROR] [1430286648.120524856]: Could not find roseus messages for posedetection_msgs under (/home/travis/ros/ws_jsk_demos/devel/share/roseus/ros /opt/ros/hydro/share/roseus/ros)
try rosrun roseus generate-all-msg-srv.sh posedetection_msgs
;; can not find nil/msg/ directory for [posedetection_msgs] packages
[ERROR] [1430286648.137471589]: Could not find roseus messages for audio_common_msgs under (/home/travis/ros/ws_jsk_demos/devel/share/roseus/ros /opt/ros/hydro/share/roseus/ros)
try rosrun roseus generate-all-msg-srv.sh audio_common_msgs
[ERROR] [1430286648.137571162]: Could not find roseus messages for audio_common_msgs under (/home/travis/ros/ws_jsk_demos/devel/share/roseus/ros /opt/ros/hydro/share/roseus/ros)
try rosrun roseus generate-all-msg-srv.sh audio_common_msgs
[ERROR] [1430286648.139560142]: Could not find roseus messages for diagnostic_msgs under (/home/travis/ros/ws_jsk_demos/devel/share/roseus/ros /opt/ros/hydro/share/roseus/ros)
try rosrun roseus generate-all-msg-srv.sh diagnostic_msgs
[ERROR] [1430286648.139632919]: Could not find roseus messages for diagnostic_msgs under (/home/travis/ros/ws_jsk_demos/devel/share/roseus/ros /opt/ros/hydro/share/roseus/ros)
try rosrun roseus generate-all-msg-srv.sh diagnostic_msgs
[ERROR] [1430286648.321581909]: Could not find roseus messages for posedetection_msgs under (/home/travis/ros/ws_jsk_demos/devel/share/roseus/ros /opt/ros/hydro/share/roseus/ros)
try rosrun roseus generate-all-msg-srv.sh posedetection_msgs
[ERROR] [1430286648.321627162]: Could not find nil/manifest.l
try rosrun roseus generate-all-msg-srv.sh posedetection_msgs
[ERROR] [1430286648.321709610]: Could not find roseus messages for posedetection_msgs under (/home/travis/ros/ws_jsk_demos/devel/share/roseus/ros /opt/ros/hydro/share/roseus/ros)
try rosrun roseus generate-all-msg-srv.sh posedetection_msgs
;; can not find nil/msg/ directory for [posedetection_msgs] packages
[ERROR] [1430286648.348107746]: Could not find roseus messages for audio_common_msgs under (/home/travis/ros/ws_jsk_demos/devel/share/roseus/ros /opt/ros/hydro/share/roseus/ros)
try rosrun roseus generate-all-msg-srv.sh audio_common_msgs
[ERROR] [1430286648.348237947]: Could not find roseus messages for audio_common_msgs under (/home/travis/ros/ws_jsk_demos/devel/share/roseus/ros /opt/ros/hydro/share/roseus/ros)
try rosrun roseus generate-all-msg-srv.sh audio_common_msgs
[ERROR] [1430286648.349846851]: Could not find roseus messages for diagnostic_msgs under (/home/travis/ros/ws_jsk_demos/devel/share/roseus/ros /opt/ros/hydro/share/roseus/ros)
try rosrun roseus generate-all-msg-srv.sh diagnostic_msgs
[ERROR] [1430286648.349919884]: Could not find roseus messages for diagnostic_msgs under (/home/travis/ros/ws_jsk_demos/devel/share/roseus/ros /opt/ros/hydro/share/roseus/ros)
try rosrun roseus generate-all-msg-srv.sh diagnostic_msgs
[ERROR] [1430286648.486194090]: Could not find roseus messages for posedetection_msgs under (/home/travis/ros/ws_jsk_demos/devel/share/roseus/ros /opt/ros/hydro/share/roseus/ros)
try rosrun roseus generate-all-msg-srv.sh posedetection_msgs
[ERROR] [1430286648.486230358]: Could not find nil/manifest.l
try rosrun roseus generate-all-msg-srv.sh posedetection_msgs
[ERROR] [1430286648.486299868]: Could not find roseus messages for posedetection_msgs under (/home/travis/ros/ws_jsk_demos/devel/share/roseus/ros /opt/ros/hydro/share/roseus/ros)
try rosrun roseus generate-all-msg-srv.sh posedetection_msgs
;; can not find nil/msg/ directory for [posedetection_msgs] packages
[ERROR] [1430286648.542116374]: Could not find roseus messages for audio_common_msgs under (/home/travis/ros/ws_jsk_demos/devel/share/roseus/ros /opt/ros/hydro/share/roseus/ros)
try rosrun roseus generate-all-msg-srv.sh audio_common_msgs
[ERROR] [1430286648.542274275]: Could not find roseus messages for audio_common_msgs under (/home/travis/ros/ws_jsk_demos/devel/share/roseus/ros /opt/ros/hydro/share/roseus/ros)
try rosrun roseus generate-all-msg-srv.sh audio_common_msgs
[ERROR] [1430286648.543884798]: Could not find roseus messages for diagnostic_msgs under (/home/travis/ros/ws_jsk_demos/devel/share/roseus/ros /opt/ros/hydro/share/roseus/ros)
try rosrun roseus generate-all-msg-srv.sh diagnostic_msgs
[ERROR] [1430286648.544053038]: Could not find roseus messages for diagnostic_msgs under (/home/travis/ros/ws_jsk_demos/devel/share/roseus/ros /opt/ros/hydro/share/roseus/ros)
try rosrun roseus generate-all-msg-srv.sh diagnostic_msgs
;; extending gcstack 0x4d43230[32738] --> 0x6f235d0[65476] top=7e5d
[ERROR] [1430286648.673895618]: Could not find roseus messages for posedetection_msgs under (/home/travis/ros/ws_jsk_demos/devel/share/roseus/ros /opt/ros/hydro/share/roseus/ros)
try rosrun roseus generate-all-msg-srv.sh posedetection_msgs
[ERROR] [1430286648.673940078]: Could not find nil/manifest.l
try rosrun roseus generate-all-msg-srv.sh posedetection_msgs
[ERROR] [1430286648.674028293]: Could not find roseus messages for posedetection_msgs under (/home/travis/ros/ws_jsk_demos/devel/share/roseus/ros /opt/ros/hydro/share/roseus/ros)
try rosrun roseus generate-all-msg-srv.sh posedetection_msgs
;; can not find nil/msg/ directory for [posedetection_msgs] packages
output to /home/travis/ros/ws_jsk_demos/build/jsk_demo_common/test_results/jsk_demo_common/rosunit-test_pick_action.xml
start testing [test-pick-action-server]
;; 15259 wait-for-server
unittest-sigint-handler 2
testtest_pick_action ... ERROR!
ERROR: test max time allotted
  File "/usr/lib/python2.7/unittest/case.py", line 327, in run
    testMethod()
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rostest/runner.py", line 146, in fn
    self.test_parent.run_test(test)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rostest/rostest_parent.py", line 91, in run_test
    return self.runner.run_test(test)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/roslaunch/launch.py", line 669, in run_test
    raise RLTestTimeoutException("test max time allotted")
--------------------------------------------------------------------------------
[ROSTEST]-----------------------------------------------------------------------
SUMMARY
 * RESULT: FAIL
 * TESTS: 0
 * ERRORS: 1
 * FAILURES: 0
rostest log file is in /home/travis/.ros/log/rostest-testing-worker-linux-380b67c9-2-17340-linux-4-60487022-15210.log
-- run_tests.py: verify result "/home/travis/ros/ws_jsk_demos/build/jsk_demo_common/test_results/jsk_demo_common/rostest-test_test_pr2_action_server.xml"
```

**Comment by furushchev** [comment]
I think this is the same problem as https://github.com/jsk-ros-pkg/jsk_roseus/pull/293
any idea?

**Comment by furushchev** [comment]
Travis failed because of the same error. It seems there is another problem.

**Comment by k-okada** [comment]
please check if this happens on your local environment

**Comment by k-okada** [comment]
also you use old .travis again

**Pull request closed without merging**
