### PR TITLE
[jsk_maps] Update 610 map

### PR DESCRIPTION
**Pull request by taichiH**
I updated 610 map and add 610 keepout map.
These files may change frequently.

### CODE REVIEW

**Comment by k-okada** [comment]
Could you show the image of the map.?

**Comment by taichiH** [comment]
ok, here are the map image files.

eng8-6f-0 05

eng8-6f-0 05_keepout

**Comment by mqcmd196** [comment]
@iory @nakane11 
Which map do you use by default? `origin/master` , https://github.com/jsk-ros-pkg/jsk_demos/pull/1277, https://github.com/jsk-ros-pkg/jsk_demos/pull/1366 ?

**Comment by nakane11** [comment]
Currently pr1012 uses `develop/pr2` of knorth55 (#1366).
#1366 includes #1277, but the maps were changed by https://github.com/jsk-ros-pkg/jsk_demos/pull/1366/commits/05175731106034742c983dc500db2677bf53c1e1.
The same as #1360??

**Comment by mqcmd196** [comment]
@nakane11 Thank you. 

@k-okada So we don't need this PR. Please merge https://github.com/jsk-ros-pkg/jsk_demos/pull/1360 and close this. I have not authorized to close it

**Pull request closed without merging**
