### PR TITLE
use pr2_navigation_self_filter

### PR DESCRIPTION
**Pull request by YutaKojio**
use pr2_navigation_self_filter when ```RUN_SELF_FILTER:=true```

### CODE REVIEW

**Comment by garaemon** [comment]
:+1:

**Comment by wkentaro** [comment]
test probably fails because of old pip.
```
+ rosdep install -r -q -n --from-paths . /opt/ros/hydro/share --ignore-src --rosdistro hydro -y
WARNING: Package "ompl" does not follow the version conventions. It should not contain leading zeros (unless the number is 0).
WARNING: Package "ompl" does not follow the version conventions. It should not contain leading zeros (unless the number is 0).
WARNING: Package "ompl" does not follow the version conventions. It should not contain leading zeros (unless the number is 0).
Usage: pip COMMAND [OPTIONS]

pip: error: No command by the name pip show
  (maybe you meant "pip install show")

ERROR: Rosdep experienced an internal error.
Please go to the rosdep page [1] and file a bug report with the message below.
[1] : http://www.ros.org/wiki/rosdep

rosdep version: 0.11.3

Bad installer [pip]: Command '['pip', 'show', 'fysom']' returned non-zero exit status 2
```

**Comment by wkentaro** [comment]
@YutaKojio 
Please update .travis after https://github.com/jsk-ros-pkg/jsk_travis/pull/155 is merged.

**Comment by YutaKojio** [comment]
travis passed thanks to https://github.com/jsk-ros-pkg/jsk_travis/pull/155
Please merge.

**Pull request merged**
