### PR TITLE
[WIP] subway demo revival

### PR DESCRIPTION
**Pull request by furushchev**
Still work in progress...

@YutoUchimi @Affonso-Gui 

Known TODOs:
- [ ] update door button pushing function (the building is updated from the last demo)
- [ ] Check if interaction in subway shop works 

How to run:

```bash
roslaunch elevator_move_base_pr2 elevator_move_base_eng2.launch
```

This advertises `/elevator_move_base/goal` and `/elevator_move_base_simple/goal`,
to set a goal via `rviz`, change the topic for `2d nav goal` to this topic:

image

Then drop the arrow, the robot will move.

To see the current robot state, please run `smach_viewer` by:

```bash
rosrun smach_viewer smach_viewer.py
```

If you want to send a goal to move_base with elavator, you will have to remap the client in `robot-interface` by running something like below:

```lisp
(defun pr2-init (&optional (create-viewer))
  (setq *pr2* (pr2)
        *ri* (instance pr2-interface :init
                       :move-base-action-name "elevator_move_base"))
```

This is a basic usage for only moving base using elavator.

To run actual subway demo, do run `roslaunch ... elevator_move_base_eng2.launch`, and then run

```bash
rosrun elevator_move_base_pr2 fetch-sandwich.l
```

### CODE REVIEW

**Comment by YutoUchimi** [comment]
- Probably not
    ```
    roslaunch elevator_move_base_pr2 elevator_move_base_pr2.launch
    ```
    but
    ```
    roslaunch elevator_move_base_pr2 elevator_move_base_eng2.launch
    ```
    Is it right?

- After executing
    ```
    rosrun elevator_move_base_pr2 fetch-sandwich.l
    ```
    PR2 went to elevator hall, but sometimes PR2 stops moving.
    Maybe cost map problem?

- After moving to in front of elevator, PR2 looked at elevator button.
    But PR2 would not push it, so I moved PR2 to 73B2 by joy-stick.

**Comment by furushchev** [comment]
@YutoUchimi Did you take a video or screencast of smach transition? I'd like to see them.

**Comment by YutoUchimi** [comment]
Sorry, I didn't take screencast of smach.
But there is a video.
@iory Could you please share it?

**Comment by iory** [comment]
OK. I'll upload it tomorrow

**Comment by Affonso-Gui** [comment]
If I remember correctly we also had the below problems:

- [ ] **Stops moving when obstacle is found.**
   Probably costmap update and/or inflation zone problem. Moves again after manually clearing the costmap or moving with the joystick
- [ ] **Fails to press the 2nd floor button on the elevator.**
  Maybe recognition is not going well, maybe it is just taking more time than it should, maybe it is simply not seeing the whole panel

**Comment by YutoUchimi** [comment]
Move to https://github.com/jsk-ros-pkg/jsk_demos/pull/1276, so we can close this.

**Pull request closed without merging**
