### PR TITLE
[DO NOT MERGE YET] Integrate vehicle launch to main stream of silverhammer

### PR DESCRIPTION
**Pull request by orikuma**
This PR should be checked in real robot because this change may cause some bad side effect.

### CODE REVIEW

**Comment by garaemon** [comment]
merge origin/master

**Comment by orikuma** [comment]
Merged origin/master but I need some bug fix.

**Comment by orikuma** [comment]
Please merge if test passed

**Comment by orikuma** [comment]
帯域制限対応が不十分なので, 修正するまでマニピュレーション時にはtmuxのvehicleのwindowを全部落としてください

**Pull request merged**
