### PR TITLE
[WIP]using elevator by Spot

### PR DESCRIPTION
**Pull request by mqcmd196**

### CODE REVIEW

**Review by k-okada — CHANGES_REQUESTED** [review]
this code should goes to jsk_spot_robot and start with bringup process.

**Comment by mqcmd196** [comment]
@k-okada Ok. Amabe-kun's demo also should move to `jsk_spot_robot` ?

**Comment by k-okada** [comment]
demo should remain in jsk_demos
--
◉ Kei Okada



2021年4月21日(水) 13:59 Yoshiki Obinata ***@***.***>:

**Comment by mqcmd196** [comment]
Okay

**Pull request closed without merging**
