### PR TITLE
[jsk_2013_04_pr2_610] add test for 610 demo with planning #1113

### PR DESCRIPTION
**Pull request by k-okada**
take over #1113
- travis.yml: add source test
- [jsk_2013_04_pr2_610] add test for 610 demo with planning

### CODE REVIEW

**Comment by k-okada** [comment]
humm, we can not find error when the it failed to launch, without https://github.com/jsk-ros-pkg/jsk_travis/pull/193

**Comment by k-okada** [comment]
using roslaunch-check may fail if the launch file is not ok

**Comment by furushchev** [comment]
Sorry I forgot to add sound_play nodes to launch/test file.
created PR to https://github.com/k-okada/jsk_demos/pull/1

**Comment by furushchev** [comment]
restarted travis

```bash

Traceback (most recent call last):
  File "./.travis/travis_jenkins.py", line 261, in 
    if j.get_plugin_info('ansicolor'):
  File "/home/travis/.local/lib/python2.7/site-packages/jenkins/__init__.py", line 561, in get_plugin_info
    plugins_info = self.get_plugins(depth)
  File "/home/travis/.local/lib/python2.7/site-packages/jenkins/__init__.py", line 599, in get_plugins
    Request(self._build_url(PLUGIN_INFO, locals()))))
  File "/home/travis/.local/lib/python2.7/site-packages/jenkins/__init__.py", line 340, in jenkins_open
    self.maybe_add_crumb(req)
  File "/home/travis/.local/lib/python2.7/site-packages/jenkins/__init__.py", line 254, in maybe_add_crumb
    self._build_url(CRUMB_URL)), add_crumb=False)
  File "/home/travis/.local/lib/python2.7/site-packages/jenkins/__init__.py", line 371, in jenkins_open
    raise JenkinsException('Error in request: %s' % (e.reason))
jenkins.JenkinsException: Error in request: [Errno 110] Connection timed out
```

**Comment by furushchev** [comment]
> travis.yml: add source test

@k-okada how do you think about hydro? (task_compiler can be installed by apt only after indigo)

**Comment by k-okada** [comment]
how about skipping on hydro like:
```
+if(CATKIN_ENABLE_TESTING AND NOT $ENV{ROS_DISTRO} STREQUAL "hydro")
```

--
◉ Kei Okada

**Comment by furushchev** [comment]
wait for https://github.com/jsk-ros-pkg/jsk_planning/pull/33

**Comment by furushchev** [comment]
waiting https://github.com/k-okada/jsk_demos/pull/5

**Comment by furushchev** [comment]
restarted 

```
Cloning into 'jenkins-trusty-travis-jsk-ros-pkg-jsk_demos-indigo-deb-true-ros-indigo-convex-decomposition-ros-indigo-ivcon-true-2088/jsk-ros-pkg/jsk_demos'...
+ cd jenkins-trusty-travis-jsk-ros-pkg-jsk_demos-indigo-deb-true-ros-indigo-convex-decomposition-ros-indigo-ivcon-true-2088/jsk-ros-pkg/jsk_demos
+ [ 1114 != false ]
+ git fetch origin +refs/pull/1114/merge
error: RPC failed; result=22, HTTP code = 408
fatal: The remote end hung up unexpectedly
```

**Comment by furushchev** [comment]
travis failed

```
testcheck_planner_launch ... FAILURE!


FAILURE: test [check_planner_launch] did not generate test results


  File "/usr/lib/python2.7/unittest/case.py", line 331, in run


    testMethod()


  File "/opt/ros/indigo/lib/python2.7/dist-packages/rostest/runner.py", line 164, in fn


    self.assert_(os.path.isfile(test_file), "test [%s] did not generate test results"%test_name)


  File "/usr/lib/python2.7/unittest/case.py", line 424, in assertTrue


    raise self.failureException(msg)

```

**Comment by furushchev** [comment]
https://github.com/jsk-ros-pkg/jsk_common/pull/1286 should fix this error.

**Comment by furushchev** [comment]
Created another PR to upstream
ros/ros_comm#716

**Comment by furushchev** [comment]
test failed on other reason.
maybe need to merge origin/master?

```
[drc_task_common] CMake Error at /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:75 (find_package): 

[drc_task_common]   Could not find a package configuration file provided by "jsk_pcl_ros" with 

[drc_task_common]   any of the following names:                                 

[drc_task_common]                                                               

[drc_task_common]     jsk_pcl_rosConfig.cmake                                   

[drc_task_common]     jsk_pcl_ros-config.cmake                                  

[drc_task_common]                                                               

[drc_task_common]   Add the installation prefix of "jsk_pcl_ros" to CMAKE_PREFIX_PATH or set 

[drc_task_common]   "jsk_pcl_ros_DIR" to a directory containing one of the above files.  If 

[drc_task_common]   "jsk_pcl_ros" provides a separate development package or SDK, be sure it 

[drc_task_common]   has been installed.                                         

[drc_task_common] Call Stack (most recent call first):                          

[drc_task_common]   CMakeLists.txt:4 (find_package)                             

[drc_task_common]                                                               

[drc_task_common]                                                               

[drc_task_common] -- Configuring incomplete, errors occurred!                   

[drc_task_common] See also "/workspace/ros/ws_jsk_demos/build/drc_task_common/CMakeFiles/CMakeOutput.log". 

[drc_task_common] See also "/workspace/ros/ws_jsk_demos/build/drc_task_common/CMakeFiles/CMakeError.log". 

[drc_task_common] <== '/workspace/ros/ws_jsk_demos/build/drc_task_common/build_env.sh /usr/bin/cmake /workspace/ros/ws_jsk_demos/src/jsk_demos/jsk_2015_06_hrp_drc/drc_task_common -DCATKIN_DEVEL_PREFIX=/workspace/ros/ws_jsk_demos/devel -DCMAKE_INSTALL_PREFIX=/workspace/ros/ws_jsk_demos/install' failed with return code '1' 

Failed   <== drc_task_common              [ 3.1 seconds ]     
```

**Comment by furushchev** [comment]
failed to apt-get ?

```
ERROR: the following rosdeps failed to install

  apt: command [sudo -H apt-get install -y -qq ros-indigo-jsk-teleop-joy] failed

  apt: Failed to detect successful installation of [ros-indigo-jsk-teleop-joy]

  apt: command [sudo -H apt-get install -y -qq ros-indigo-jsk-pcl-ros] failed

  apt: command [sudo -H apt-get install -y -qq ros-indigo-jsk-interactive-marker] failed

  apt: command [sudo -H apt-get install -y -qq ros-indigo-jsk-pr2-startup] failed

  apt: command [sudo -H apt-get install -y -qq ros-indigo-jsk-footstep-planner] failed

  apt: command [sudo -H apt-get install -y -qq ros-indigo-jsk-footstep-controller] failed

  apt: Failed to detect successful installation of [ros-indigo-jsk-interactive-marker]

  apt: Failed to detect successful installation of [ros-indigo-jsk-footstep-controller]

  apt: Failed to detect successful installation of [ros-indigo-jsk-footstep-planner]

  apt: Failed to detect successful installation of [ros-indigo-jsk-pr2-startup]

  apt: Failed to detect successful installation of [ros-indigo-jsk-pcl-ros]
```

**Comment by furushchev** [comment]
we must only wait

```
sudo -H apt-get install -y -qq ros-indigo-jsk-pcl-ros            ⮂
E: Package 'ros-indigo-jsk-pcl-ros' has no installation candidate
```

**Comment by furushchev** [comment]
#1211 took over this pull request. I think it's ok to close.

**Pull request closed without merging**
