### PR TITLE
[jsk_maps] Fix fetch_dock_position

### PR DESCRIPTION
**Pull request by sktometometo**
Fix Fetch's docking station position wrongly changed by https://github.com/jsk-ros-pkg/jsk_demos/pull/1381.

### CODE REVIEW

**Comment by k-okada** [comment]
```
.github/workflows/config.yml / ros (noetic, jskrobotics/ros-ubuntu:20.04-pcl, python3-rospkg python3-rospkg-modules) (pull_request) Failing after 12m
```
The noetic test is expected to fail (that's why it does not 'required'), so if someone confirm this PR, then we're ready to merge.

Regarding the noteic test, see  https://github.com/jsk-ros-pkg/jsk_demos/pull/1390

**Comment by sktometometo** [comment]
@mqcmd196 @Kanazawanaoaki @tkmtnt7000 Could you review this PR?

**Comment by mqcmd196** [comment]
Before the PR
image

After the PR
image

And the other spots are reasonable
image

**Comment by mqcmd196** [comment]
When checking on my local PC, https://github.com/jsk-ros-pkg/jsk_demos/pull/1361 was helpful.

**Review by tkmtnt7000 — COMMENTED** [review]
This is just a comment and I think this PR is OK.

I don't know why this change was made before, since there is no explanation in this code, but I assume that he wanted to define the location just before approaching the dock, rather than  the position of the Fetch dock itself.
Perhaps, it may also be good to update this file and to set the Fetch dock position itself.
https://github.com/jsk-ros-pkg/jsk_robot/blob/f08427720dd2e467485aba4717d9779b87f3718e/jsk_fetch_robot/jsk_fetch_startup/scripts/correct_position.py#L21-L24

**Comment by knorth55** [comment]
FYI:
@tkmtnt7000 you are right.
i made the spot not for dock place, but for dock's approach position.
for that reason, i named it as `dock-front`.

**Pull request merged**
