### PR TITLE
[WIP][Spot] Spot's person following demo

### PR DESCRIPTION
**Pull request by sktometometo**
This demo enables Spot to follow person.

https://user-images.githubusercontent.com/9410362/112797926-1ae3b180-90a7-11eb-892a-21e9df53716e.mp4

## Prerequities

This demo requires packages below.

- [spot_ros]() with [this patch](https://github.com/clearpathrobotics/spot_ros/pull/25)
- [common_msgs]() with [this patch](https://github.com/ros/common_msgs/pull/171)
- [jsk_recognition]() with [this patch](https://github.com/jsk-ros-pkg/jsk_recognition/pull/2579) and [this patch](https://github.com/jsk-ros-pkg/jsk_recognition/pull/2581)
- [jsk_spot_startup]() with [this patch](https://github.com/jsk-ros-pkg/jsk_robot/pull/1325)

## How to run

Before running this demo, please launch and prepair a controller.

- `jsk_spot_bringup.launch`
- `object_detection_and_tracking.launch`
- `multi_object_detector.launch`

And then, please run

```bash
roslaunch spot_person_follower demo.launch
```

After this, you can start following behavior by pressing L2 button of the controller.
Spot will follow the nearest person at the time of pressing.
If you want to stop the behavior, please press the L2 button again.

### CODE REVIEW

**Comment by k-okada** [comment]
@sktometometo 
where is the node to publish `/spot_recognition/bbox_array, /spot_recognition/tracking_labels` ?

Cc: @tongtybj

**Comment by tongtybj** [comment]
@sktometometo 

Please add the node of human tracking in your launch file, and I strongly recommend to clean up you commits. 
Comments like "fix bugs", "update" are trivival. Please specify what kind of bugs or updates you address. 
Also please add description for this PR.

BTW, I am very interesting with this demo. Can I try today or tomorrow?

**Comment by sktometometo** [comment]
@k-okada @tongtybj
This demo requires outputs of [`rect_array_in_panorama_to_bounding_box_array node`](https://github.com/jsk-ros-pkg/jsk_recognition/pull/2581) in `object_detection_and_tracking.launch` and `deep_sort_tracker_node.py` in `multi_object_tracker.launch`. Currently, both launch files are in [`jsk_spot_startup` packgae](https://github.com/jsk-ros-pkg/jsk_robot/pull/1325).

Sorry for dirty commit history, this is a develop branch.
Now this demo works. So I will clean up commits and add descriptions.

I will go to the lab in today's evening.

**Comment by tongtybj** [comment]
@sktometometo 

I also plan to go to lab today.
Can you show this demo at that time?

**Comment by sktometometo** [comment]
@tongtybj
Yes, I can show you current demo. No problem.

**Comment by k-okada** [comment]
@sktometometo do you have a bag file for this demo?  @tongtybj is creating tracking node and he will create sample launch files that publish 3D person / human / cara trajectory.

**Comment by sktometometo** [comment]
I think rosbag files in [this grive directory](https://drive.google.com/drive/folders/1WP7uYREhFXLpScHG6sOtu15ob0n7e2Kw?usp=sharing) can be used.

In order to reproduce recognition fuction of Spot, you need 2 ROS workspaces because these rosbag files only contains outputs of sensor data and currently object detection is done by [coral_usb_ros](https://github.com/knorth55/coral_usb_ros)
First one can be created with rosinstall file in [my PR](https://github.com/jsk-ros-pkg/jsk_robot/pull/1325) ( [README.md](https://github.com/sktometometo/jsk_robot/tree/develop/spot/jsk_spot_robot) file describes how to create a workspace for spot).
Second one have to include [coral_usb_ros](https://github.com/knorth55/coral_usb_ros), [jsk_robot with my PR](https://github.com/jsk-ros-pkg/jsk_robot/pull/1325), [jsk_perception with my PR about `rect_array_in_panorama_to_bounding_box_array`](https://github.com/jsk-ros-pkg/jsk_recognition/pull/2581).

In order to play, please run three launch files.
```bash
# In the first workspace
roslaunch jsk_spot_startup play.launch rosbag:=<absolute path to rosbag>
```

```bash
# In the second workspace
roslaunch jsk_spot_startup object_detection_and_tracking.launch
```

```bash
# In the first workspace
roslaunch jsk_spot_startup multi_object_tracker.launch
```

The third launch file requires CUDA and chainer <= 6.7.0

**Comment by tongtybj** [comment]
@sktometometo 

Thank you for your kind instruction.

So, from my understanding, 
object detection (from coral_usb_ros)  is used to provide the first bounding box to feed and start deep_sorted_tracker, right?
And, why you need two ros worksapce, it that coral_sub_ros is based on python3, right?

I am developing a new tracker: https://github.com/tongtybj/detr, and I am going to try this new tracker with your rosbag data first. 
Hope my new tracker can outperform the deep_sort_tracker.

**Comment by sktometometo** [comment]
@tongtybj 
rect_array_in_panorama_to_bounding_box_array and deep_sort_tracker runs independently since deep_sort_tracker use only object detection’s result
in 2D image plane.
Integration of multi object tracking and 3D geometric information is done in this demo.

**Comment by sktometometo** [comment]
and yes, coral_usb_ros requires python3 and we needs to create 2 ROS workspaces

**Comment by k-okada** [comment]
@sktometometo I think you can create bag file that includes images and `/edgetpu_human_pose_estimator/output/poses`, so that @tongtybj can skip workspace settings.

**Comment by sktometometo** [comment]
@k-okada Ok I wilv creat it later

**Comment by sktometometo** [comment]
Moved to https://github.com/jsk-ros-pkg/jsk_demos/pull/1343

**Pull request closed without merging**
