### PR TITLE
Move template feature from jsk perception

### PR DESCRIPTION
**Pull request by furushchev**
ref: https://github.com/jsk-ros-pkg/jsk_recognition/pull/702

### CODE REVIEW

**Comment by furushchev** [comment]
travis passed. please merge

**Comment by k-okada** [comment]
this means that other demo program will depends on `elevetor_move_base_pr2`
program when they want to recognize something, say turtlebot, is it correct?

--
◉ Kei Okada

**Comment by furushchev** [comment]
this is discussed at https://github.com/jsk-ros-pkg/jsk_recognition/pull/702
So what should I do?

**Comment by garaemon** [comment]
How about put euslisp files into jsk_perception and run cmake from jsk_demos package.
I don't want to run euslisp in jsk_recognition until geneus is to be stable.

**Comment by garaemon** [comment]
it's not correct, euslisp is OK now but I don't want to depend on roseus and geneus now.

@furushchev Can the script run without roseus and geneus?

**Comment by garaemon** [comment]
These days I heavily used the latest euslisp/roseus/geneus and I agree that they are being stable enough.

* https://github.com/jsk-ros-pkg/jsk_roseus/pull/236

After solving this issue, I'm willing to depend on roseus from jsk_perception.

**Pull request closed without merging**
