### PR TITLE
[detect_cans] add README

### PR DESCRIPTION
**Pull request by h-kamada**
added README of fridge demo.

### CODE REVIEW

**Comment by h-kamada** [comment]
related to #1115

**Comment by k-okada** [comment]
please add nice images like
https://github.com/jsk-ros-pkg/jsk_demos/tree/master/jsk_2013_04_pr2_610

--
◉ Kei Okada

**Comment by h-kamada** [comment]
added pictures of executing fridge demo in simulation mode!

**Comment by k-okada** [comment]
did you capture the screen shot by
Control + Alt + PrtSc ?
if it does not work,  try
`gnome-screenshot  --window -d 3`
or
`gnome-screenshot  -i`

--
◉ Kei Okada

**Comment by h-kamada** [comment]
fixed!

**Comment by k-okada** [comment]
nice!,
can you use width=300x (?) to show images in 2x2 format
http://stackoverflow.com/questions/14675913/how-to-change-image-size-markdown

--
◉ Kei Okada

**Comment by h-kamada** [comment]
fixed

**Pull request merged**
