### PR TITLE
Update travis

### PR DESCRIPTION
**Pull request by garaemon**

### CODE REVIEW

**Comment by garaemon** [comment]
Who does depend on roslint?

```
]2;[build] 7/23]2;[build] 7/23]2;[build] 7/23]2;[build] 7/23]2;[build] 7/23]2;[build] 7/23[pr2eus] [ 50%] Generating EusLisp manifest code for pr2eus                     
]2;[build] 7/23]2;[build] 7/23]2;[build] 7/23]2;[build] 7/23]2;[build] 7/23]2;[build] 7/23]2;[build] 7/23[pr2eus] Traceback (most recent call last):                                     
]2;[build] 7/23[pr2eus]   File "/opt/ros/hydro/lib/python2.7/dist-packages/geneus/geneus_main.py", line 79, in genmain 
]2;[build] 7/23[pr2eus]     for p in r.get_depends(pkg):                                       
]2;[build] 7/23[pr2eus]   File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 236, in get_depends 
]2;[build] 7/23[pr2eus]     s.update(self.get_depends(p, implicit))                            
]2;[build] 7/23[pr2eus]   File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 236, in get_depends 
]2;[build] 7/23[pr2eus]     s.update(self.get_depends(p, implicit))                            
]2;[build] 7/23[pr2eus]   File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 236, in get_depends 
]2;[build] 7/23[pr2eus]     s.update(self.get_depends(p, implicit))                            
]2;[build] 7/23[pr2eus]   File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 230, in get_depends 
]2;[build] 7/23[pr2eus]     names = [p.name for p in self.get_manifest(name).depends]          
]2;[build] 7/23[pr2eus]   File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 163, in get_manifest 
]2;[build] 7/23[pr2eus]     return self._load_manifest(name)                                   
]2;[build] 7/23[pr2eus]   File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 207, in _load_manifest 
]2;[build] 7/23[pr2eus]     retval = self._manifests[name] = parse_manifest_file(self.get_path(name), self._manifest_name, rospack=self) 
]2;[build] 7/23[pr2eus]   File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 199, in get_path 
]2;[build] 7/23[pr2eus]     raise ResourceNotFound(name, ros_paths=self._ros_paths)            
]2;[build] 7/23[pr2eus] ResourceNotFound: roslint                                              
```

**Comment by k-okada** [comment]
as far as  I know,
https://github.com/start-jsk/rtmros_hironx/blob/hydro-devel/hironx_ros_bridge/package.xml

--
◉ Kei Okada

**Comment by garaemon** [comment]
The error comes from pr2eus.

```
]2;[build] 7/23]2;[build] 7/23]2;[build] 7/23]2;[build] 7/23]2;[build] 7/23]2;[build] 7/23[pr2eus] [ 50%] Generating EusLisp manifest code for pr2eus                     
]2;[build] 7/23]2;[build] 7/23]2;[build] 7/23]2;[build] 7/23]2;[build] 7/23]2;[build] 7/23]2;[build] 7/23[pr2eus] Traceback (most recent call last):                                     
]2;[build] 7/23[pr2eus]   File "/opt/ros/hydro/lib/python2.7/dist-packages/geneus/geneus_main.py", line 79, in genmain 
]2;[build] 7/23[pr2eus]     for p in r.get_depends(pkg):                                       
]2;[build] 7/23[pr2eus]   File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 236, in get_depends 
]2;[build] 7/23[pr2eus]     s.update(self.get_depends(p, implicit))                            
]2;[build] 7/23[pr2eus]   File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 236, in get_depends 
]2;[build] 7/23[pr2eus]     s.update(self.get_depends(p, implicit))                            
]2;[build] 7/23[pr2eus]   File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 236, in get_depends 
]2;[build] 7/23[pr2eus]     s.update(self.get_depends(p, implicit))                            
]2;[build] 7/23[pr2eus]   File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 230, in get_depends 
]2;[build] 7/23[pr2eus]     names = [p.name for p in self.get_manifest(name).depends]          
]2;[build] 7/23[pr2eus]   File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 163, in get_manifest 
]2;[build] 7/23[pr2eus]     return self._load_manifest(name)                                   
]2;[build] 7/23[pr2eus]   File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 207, in _load_manifest 
]2;[build] 7/23[pr2eus]     retval = self._manifests[name] = parse_manifest_file(self.get_path(name), self._manifest_name, rospack=self) 
]2;[build] 7/23[pr2eus]   File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 199, in get_path 
]2;[build] 7/23[pr2eus]     raise ResourceNotFound(name, ros_paths=self._ros_paths)            
]2;[build] 7/23[pr2eus] ResourceNotFound: roslint                                              
```

**Comment by garaemon** [comment]
@k-okada we need to wait for newer geneus release?

**Comment by k-okada** [comment]
I just confirm new geneus is released. This should be ok, and I'll test on https://github.com/jsk-ros-pkg/jsk_demos/pull/279 PR, I'll let you know if it is ok.

**Pull request closed without merging**
