### PR TITLE
[WIP] Update map of eng2-8f, add room 83A3

### PR DESCRIPTION
**Pull request by taichiH**
Add 83A3 map to eng2-8f map.
I confirmed Aero can go to elevator from inside of room 83A3 using this map.

### CODE REVIEW

**Comment by iory** [comment]
Could you show the image of the map.

**Comment by taichiH** [comment]
Thanks for your advise, this is the new map.
eng2-8f-0 05

**Comment by k-okada** [comment]
why you close this? @taichiH

**Comment by taichiH** [comment]
I closed this by mistake.

**Comment by taichiH** [comment]
Because room 83A3 isn't used now, please close this PR.

**Pull request merged**
