### PR TITLE
[jsk_2013_04_pr2_610] fix dependency for 610 demo

### PR DESCRIPTION
**Pull request by furushchev**

### CODE REVIEW

**Comment by furushchev** [comment]
`laser_filter_jsk_patch` is not yet released on indigo?

```
[jsk_2013_04_pr2_610] CMake Error at /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:75 (find_package): 

[jsk_2013_04_pr2_610]   Could not find a package configuration file provided by 

[jsk_2013_04_pr2_610]   "laser_filters_jsk_patch" with any of the following names: 

[jsk_2013_04_pr2_610]                                                           

[jsk_2013_04_pr2_610]     laser_filters_jsk_patchConfig.cmake                   

[jsk_2013_04_pr2_610]     laser_filters_jsk_patch-config.cmake                  
```

**Comment by k-okada** [comment]
No

Hope we do not need them any more, ask @aginika
https://github.com/jsk-ros-pkg/jsk_3rdparty/issues/11

--
◉ Kei Okada

2015/10/06 14:54、Furushchev <notifications@github.com> のメッセージ:

**Comment by aginika** [comment]
@furushchev I'm not sure whether the PR I sent is related to the laser_filters_jsk_patch, but if so, I sent it and it merged already.

**Comment by furushchev** [comment]
@k-okada @aginika I think this is not just patch, but also added another plugins for laser_filter like below:
https://github.com/jsk-ros-pkg/jsk_3rdparty/blob/master/jsk_ros_patch/laser_filters_jsk_patch/laser_filters_plugins.xml#L3
@aginika need to PR for this plugin to upstream?

**Comment by furushchev** [comment]
ping

**Comment by k-okada** [comment]
do we need to release laser_filter_jsk_patch, to indigo?

--
◉ Kei Okada

**Comment by furushchev** [comment]
@aginika 
> do we need to release laser_filter_jsk_patch, to indigo?

**Comment by aginika** [comment]
I don't think the laser_filter_jsk_patch will be merged in upstream, because it is very niche usage....
How about creating jsk_laser_filters in jsk_recognition?

**Comment by k-okada** [comment]
added PR for foot scan filter -> https://github.com/ros-perception/laser_filters/pull/31

**Comment by k-okada** [comment]
released <== Pull request opened at: https://github.com/ros/rosdistro/pull/9838

**Comment by furushchev** [comment]
@k-okada @aginika Thanks for cooperation. Now test passed for executing this demo in indigo.

**Comment by furushchev** [comment]
@k-okada Updated branch, and travis passed.
Please merge if there is no problem.

**Comment by furushchev** [comment]
@k-okada Thank you very much!

**Pull request merged**
