### PR TITLE
[jsk_maps/src/eng2-rooms.l] add eng2 wall / elevatorhall

### PR DESCRIPTION
**Pull request by furushchev**
elev

This PR requires https://github.com/euslisp/EusLisp/pull/145

### CODE REVIEW

**Comment by furushchev** [comment]
```
Successfully installed multi-key-dict pbr python-jenkins six
+++./.travis/travis_jenkins.py

TRAVIS_BRANCH        = master
TRAVIS_COMMIT        = 235da2101f01f75fe14ea3cb4044889eafe299ec
TRAVIS_PULL_REQUEST  = 1105
TRAVIS_REPO_SLUG     = jsk-ros-pkg/jsk_demos
TRAVIS_BUILD_ID      = 88499467
TRAVIS_BUILD_NUMBER  = 2461
TRAVIS_JOB_ID        = 88499468
TRAVIS_JOB_NUMBER    = 2461.1
TRAVIS_BRANCH        = master
ROS_DISTRO       = hydro
ROSWS            = wstool
BUILDER          = catkin
USE_DEB          = true
EXTRA_DEB        = ros-hydro-convex-decomposition ros-hydro-ivcon
TEST_PKGS        = 
TARGET_PKGS       = 
BEFORE_SCRIPT      = 
NOT_TEST_INSTALL = true
ROS_PARALLEL_JOBS       = -j1
CATKIN_PARALLEL_JOBS    = -p1
ROS_PARALLEL_TEST_JOBS  = -j1
CATKIN_PARALLEL_TEST_JOBS = -p1
BUILD_PKGS       = 

next build number is 808
wait for trusty-travis-jsk-ros-pkg-jsk_demos-hydro-deb-true-ros-hydro-convex-decomposition-ros-hydro-ivcon-true 808
start building, wait for result....
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/trusty-travis-jsk-ros-pkg-jsk_demos-hydro-deb-true-ros-hydro-convex-decomposition-ros-hydro-ivcon-true/808/ building.. True result... None
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/trusty-travis-jsk-ros-pkg-jsk_demos-hydro-deb-true-ros-hydro-convex-decomposition-ros-hydro-ivcon-true/808/ building.. True result... None
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/trusty-travis-jsk-ros-pkg-jsk_demos-hydro-deb-true-ros-hydro-convex-decomposition-ros-hydro-ivcon-true/808/ building.. True result... None
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/trusty-travis-jsk-ros-pkg-jsk_demos-hydro-deb-true-ros-hydro-convex-decomposition-ros-hydro-ivcon-true/808/ building.. True result... None
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/trusty-travis-jsk-ros-pkg-jsk_demos-hydro-deb-true-ros-hydro-convex-decomposition-ros-hydro-ivcon-true/808/ building.. True result... None
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/trusty-travis-jsk-ros-pkg-jsk_demos-hydro-deb-true-ros-hydro-convex-decomposition-ros-hydro-ivcon-true/808/ building.. True result... None
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/trusty-travis-jsk-ros-pkg-jsk_demos-hydro-deb-true-ros-hydro-convex-decomposition-ros-hydro-ivcon-true/808/ building.. True result... None
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/trusty-travis-jsk-ros-pkg-jsk_demos-hydro-deb-true-ros-hydro-convex-decomposition-ros-hydro-ivcon-true/808/ building.. True result... None
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/trusty-travis-jsk-ros-pkg-jsk_demos-hydro-deb-true-ros-hydro-convex-decomposition-ros-hydro-ivcon-true/808/ building.. True result... None
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/trusty-travis-jsk-ros-pkg-jsk_demos-hydro-deb-true-ros-hydro-convex-decomposition-ros-hydro-ivcon-true/808/ building.. True result... None


Your test run exceeded 50 minutes.
```

**Comment by furushchev** [comment]
```
error: RPC failed; result=22, HTTP code = 408
fatal: The remote end hung up unexpectedly
+ pwd
/var/lib/jenkins/jobs/trusty-travis-jsk-ros-pkg-jsk_demos-hydro-deb-true-ros-hydro-convex-decomposition-ros-hydro-ivcon-true/workspace/jenkins-trusty-travis-jsk-ros-pkg-jsk_demos-hydro-deb-true-ros-hydro-convex-decomposition-ros-hydro-ivcon-true-811/jsk-ros-pkg/jsk_demos
+ sudo rm -fr /var/lib/jenkins/jobs/trusty-travis-jsk-ros-pkg-jsk_demos-hydro-deb-true-ros-hydro-convex-decomposition-ros-hydro-ivcon-true/workspace/jenkins-trusty-travis-jsk-ros-pkg-jsk_demos-hydro-deb-true-ros-hydro-convex-decomposition-ros-hydro-ivcon-true-811
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

failed because of jenkins?

**Comment by k-okada** [comment]
restarted travis, hope this is just because of the network was down at that moment.

**Comment by furushchev** [comment]
the first error is back

```
next build number is 814
wait for trusty-travis-jsk-ros-pkg-jsk_demos-hydro-deb-true-ros-hydro-convex-decomposition-ros-hydro-ivcon-true 814
start building, wait for result....
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/trusty-travis-jsk-ros-pkg-jsk_demos-hydro-deb-true-ros-hydro-convex-decomposition-ros-hydro-ivcon-true/814/ building.. True result... None
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/trusty-travis-jsk-ros-pkg-jsk_demos-hydro-deb-true-ros-hydro-convex-decomposition-ros-hydro-ivcon-true/814/ building.. True result... None
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/trusty-travis-jsk-ros-pkg-jsk_demos-hydro-deb-true-ros-hydro-convex-decomposition-ros-hydro-ivcon-true/814/ building.. True result... None
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/trusty-travis-jsk-ros-pkg-jsk_demos-hydro-deb-true-ros-hydro-convex-decomposition-ros-hydro-ivcon-true/814/ building.. True result... None
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/trusty-travis-jsk-ros-pkg-jsk_demos-hydro-deb-true-ros-hydro-convex-decomposition-ros-hydro-ivcon-true/814/ building.. True result... None
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/trusty-travis-jsk-ros-pkg-jsk_demos-hydro-deb-true-ros-hydro-convex-decomposition-ros-hydro-ivcon-true/814/ building.. True result... None
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/trusty-travis-jsk-ros-pkg-jsk_demos-hydro-deb-true-ros-hydro-convex-decomposition-ros-hydro-ivcon-true/814/ building.. True result... None
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/trusty-travis-jsk-ros-pkg-jsk_demos-hydro-deb-true-ros-hydro-convex-decomposition-ros-hydro-ivcon-true/814/ building.. True result... None
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/trusty-travis-jsk-ros-pkg-jsk_demos-hydro-deb-true-ros-hydro-convex-decomposition-ros-hydro-ivcon-true/814/ building.. True result... None
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/trusty-travis-jsk-ros-pkg-jsk_demos-hydro-deb-true-ros-hydro-convex-decomposition-ros-hydro-ivcon-true/814/ building.. True result... None


Your test run exceeded 50 minutes. 
```

@k-okada @wkentaro Is it possible to know what is happening on jenkins? I think we cannot debug from too few hint.

**Comment by wkentaro** [comment]
docket restart?

2015年11月3日火曜日、Furushchev<notifications@github.com>さんは書きました:

> the first error is back
>
> next build number is 814
> wait for trusty-travis-jsk-ros-pkg-jsk_demos-hydro-deb-true-ros-hydro-convex-decomposition-ros-hydro-ivcon-true 814
> start building, wait for result....http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/trusty-travis-jsk-ros-pkg-jsk_demos-hydro-deb-true-ros-hydro-convex-decomposition-ros-hydro-ivcon-true/814/ building.. True result... Nonehttp://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/trusty-travis-jsk-ros-pkg-jsk_demos-hydro-deb-true-ros-hydro-convex-decomposition-ros-hydro-ivcon-true/814/ building.. True result... Nonehttp://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/trusty-travis-jsk-ros-pkg-jsk_demos-hydro-deb-true-ros-hydro-convex-decomposition-ros-hydro-ivcon-true/814/ building.. True result... Nonehttp://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/trusty-travis-jsk-ros-pkg-jsk_demos-hydro-deb-true-ros-hydro-convex-decomposition-ros-hydro-ivcon-true/814/ building.. True result... Nonehttp://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/trusty-travis-jsk-ros-pkg-jsk_demos-hydro-deb-true-ros-hydro-convex-decomposition-ros-hydro-ivcon-true/814/ building.. True result... Nonehttp://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/trusty-travis-jsk-ros-pkg-jsk_demos-hydro-deb-true-ros-hydro-convex-decomposition-ros-hydro-ivcon-true/814/ building.. True result... Nonehttp://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/trusty-travis-jsk-ros-pkg-jsk_demos-hydro-deb-true-ros-hydro-convex-decomposition-ros-hydro-ivcon-true/814/ building.. True result... Nonehttp://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/trusty-travis-jsk-ros-pkg-jsk_demos-hydro-deb-true-ros-hydro-convex-decomposition-ros-hydro-ivcon-true/814/ building.. True result... Nonehttp://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/trusty-travis-jsk-ros-pkg-jsk_demos-hydro-deb-true-ros-hydro-convex-decomposition-ros-hydro-ivcon-true/814/ building.. True result... Nonehttp://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/trusty-travis-jsk-ros-pkg-jsk_demos-hydro-deb-true-ros-hydro-convex-decomposition-ros-hydro-ivcon-true/814/ building.. True result... None
>
>
> Your test run exceeded 50 minutes.
>
> @k-okada <https://github.com/k-okada> @wkentaro
> <https://github.com/wkentaro> Is it possible to know what is happening on
> jenkins? I think we cannot debug from too few hint.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_demos/pull/1105#issuecomment-153340670>
> .
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com

**Comment by wkentaro** [comment]
It seems that jenkins is down according to the errors.

**Pull request closed without merging**
