### PR TITLE
travis: drop hydro

### PR DESCRIPTION
**Pull request by furushchev**
Since this repository is tested only on hydro, I added indigo to test and dropped hydro instead.

### CODE REVIEW

**Comment by furushchev** [comment]
test failed on indigo.

```xml
+ catkin_test_results --verbose --all build
Skipping "catkin_tools_prebuild/package.xml": 'tests'
Full test results for 'elevator_move_base_pr2/test_results/elevator_move_base_pr2/MISSING-rostest-test_test-panel-pose-detection.xml'
-------------------------------------------------
<?xml version="1.0" encoding="UTF-8"?>
<testsuite tests="1" failures="1" time="1" errors="0" name="rostest-test_test-panel-pose-detection.xml">
  <testcase name="test_ran" status="run" time="1" classname="Results">
    <failure message="Unable to find test results for rostest-test_test-panel-pose-detection.xml, test did not run.
Expected results in /workspace/ros/ws_jsk_demos/build/elevator_move_base_pr2/test_results/elevator_move_base_pr2/rostest-test_test-panel-pose-detection.xml" type=""/>
  </testcase>
</testsuite>
-------------------------------------------------
Full test results for 'elevator_move_base_pr2/test_results/elevator_move_base_pr2/MISSING-rostest-test_test-button-light.xml'
-------------------------------------------------
<?xml version="1.0" encoding="UTF-8"?>
<testsuite tests="1" failures="1" time="1" errors="0" name="rostest-test_test-button-light.xml">
  <testcase name="test_ran" status="run" time="1" classname="Results">
    <failure message="Unable to find test results for rostest-test_test-button-light.xml, test did not run.
Expected results in /workspace/ros/ws_jsk_demos/build/elevator_move_base_pr2/test_results/elevator_move_base_pr2/rostest-test_test-button-light.xml" type=""/>
  </testcase>
</testsuite>
-------------------------------------------------
Full test results for 'jsk_2013_04_pr2_610/test_results/jsk_2013_04_pr2_610/rosunit-jsk_2013_04_pr2_610_test.xml'
-------------------------------------------------
<testsuite tests="2" failures="1" disabled="0" errors="0" time="0" name="AllTests">
  <testcase name="all-test" status="run" time="0" classname="all-test">
   <failure message="signal-handler 2" type="AssertionError">
Test:""
Trace:0
Message:"signal-handler 2"
   </failure>
  </testcase>
  <testcase name="test-demo" status="run" time="0" classname="test-demo">
  </testcase>
</testsuite>

-------------------------------------------------
Full test results for 'jsk_2013_04_pr2_610/test_results/jsk_2013_04_pr2_610/rostest-test_test-demo.xml'
-------------------------------------------------
<?xml version="1.0" encoding="utf-8"?>
<testsuite errors="1" failures="0" name="unittest.suite.TestSuite" tests="1" time="601.178">
  <testcase classname="rostest.runner.RosTest" name="testjsk_2013_04_pr2_610_test" time="601.1780">
    <error type="RLTestTimeoutException">max time [600.0s] allotted for test [jsk_2013_04_pr2_610_test] of type [jsk_2013_04_pr2_610/test-demo.l]
  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rostest/runner.py", line 148, in fn
    self.test_parent.run_test(test)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rostest/rostest_parent.py", line 132, in run_test
    return self.runner.run_test(test)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/launch.py", line 681, in run_test
    (test.time_limit, test.test_name, test.package, test.type))
    </error>
  </testcase>
  <system-out><![CDATA[[ROSTEST]setup[/workspace/ros/ws_jsk_demos/src/jsk_demos/jsk_2013_04_pr2_610/test/test-demo.test] run_id[9c303096-bf46-11e7-a18d-0242ac110002] starting
?[1mstarted roslaunch server http://ac05c9f3e34e:60801/?[0m
```

**Comment by furushchev** [comment]
```bash
[elevator_move_base_pr2:make] [ERROR] [1509934749.592943456]: Skipping XML Document "/opt/ros/indigo/share/gmapping/nodelet_plugins.xml" which had no Root Element.  This likely means the XML is malformed or missing.                                                                             
[elevator_move_base_pr2:make] Traceback (most recent call last):                                                                             
[elevator_move_base_pr2:make]   File "/opt/ros/indigo/share/rostest/cmake/../../../bin/rostest", line 36, in <module>                                                                             
[elevator_move_base_pr2:make]     rostestmain()                                                                             
[elevator_move_base_pr2:make]   File "/opt/ros/indigo/lib/python2.7/dist-packages/rostest/__init__.py", line 274, in rostestmain                                                                          
[elevator_move_base_pr2:make]     _main()                                                                             
[elevator_move_base_pr2:make]   File "/opt/ros/indigo/lib/python2.7/dist-packages/rostest/rostest_main.py", line 159, in rostestmain                                                                             
[elevator_move_base_pr2:make]     testCase = rostest.runner.createUnitTest(pkg, test_file, options.reuse_master, options.clear, options.results_base_dir)                                                                             
[elevator_move_base_pr2:make]   File "/opt/ros/indigo/lib/python2.7/dist-packages/rostest/runner.py", line 229, in createUnitTest                                                                          
[elevator_move_base_pr2:make]     config = roslaunch.parent.load_config_default([test_file], None)                                                                             
[elevator_move_base_pr2:make]   File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/config.py", line 453, in load_config_default                                                                          
[elevator_move_base_pr2:make]     raise RLException(e)                                                                             
[elevator_move_base_pr2:make] roslaunch.core.RLException: while processing /workspace/ros/ws_jsk_demos/src/jsk_demos/elevator_move_base_pr2/launch/elevator_move_base_modules.xml:                                                                             
[elevator_move_base_pr2:make] while processing /opt/ros/indigo/share/jsk_perception/launch/eusmodel_detection_elevator-panels-eng2.launch:                                                                             
[elevator_move_base_pr2:make] while processing /tmp/binarydeb/ros-indigo-jsk-perception-1.2.2//template/_70639f8_elevator_call_panel.xml:                                                                             
[elevator_move_base_pr2:make] Invalid roslaunch XML syntax: [Errno 2] No such file or directory: u'/tmp/binarydeb/ros-indigo-jsk-perception-1.2.2//template/_70639f8_elevator_call_panel.xml'                                                                             
[elevator_move_base_pr2:make] Cannot find results, writing failure results to '/workspace/ros/ws_jsk_demos/build/elevator_move_base_pr2/test_results/elevator_move_base_pr2/MISSING-rostest-test_test-panel-pose-detection.xml'
```

**Comment by furushchev** [comment]
waiting for https://github.com/jsk-ros-pkg/jsk_recognition/milestone/7

**Comment by k-okada** [comment]
still failing....

**Comment by furushchev** [comment]
```bash
[elevator_move_base_pr2:make] [ERROR] [1515808463.609032085, 1324259815.944607634]: Failed to load nodelet [/pcl_nodelet/voxelgrid] of type [pcl/VoxelGrid] even after refreshing the cache: According to the loaded plugin descriptions the class pcl/VoxelGrid with base class type nodelet::Nodelet does not exist. Declared types are  adding_images/adding_images camshift/camshift contour_moments/contour_moments convex_hull/convex_hull corner_harris/corner_harris depth_image_proc/convert_metric depth_image_proc/crop_foremost depth_image_proc/disparity depth_image_proc/point_cloud_xyz depth_image_proc/point_cloud_xyz_radial depth_image_proc/point_cloud_xyzi depth_image_proc/point_cloud_xyzi_radial depth_image_proc/point_cloud_xyzrgb depth_image_proc/register discrete_fourier_transform/discrete_fourier_transform edge_detection/edge_detection face_detection/face_detection face_recognition/face_recognition fback_flow/fback_flow find_contours/find_contours general_contours/general_contours goodfeature_track/goodfeature_track hls_color_filter/hls_color_filter hough_circles/hough_circles hough_lines/hough_lines hsv_color_filter/hsv_color_filter image_proc/crop_decimate image_proc/crop_nonZero image_proc/crop_non_zero image_proc/debayer image_proc/rectify image_proc/resize image_view/disparity image_view/image imagesift/ImageSift jsk_pcl/AddColorFromImage jsk_pcl/AddColorFromImageToOrganized jsk_pcl/AddPointIndices jsk_pcl/AttentionClipper jsk_pcl/BilateralFilter jsk_pcl/BorderEstimator jsk_pcl/BoundingBoxFilter jsk_pcl/BoundingBoxOcclusionRejector jsk_pcl/CaptureStereoSynchronizer jsk_pcl/CentroidPublisher jsk_pcl/ClusterPointIndicesDecomposer jsk_pcl/ClusterPointIndicesDecomposerZAxis jsk_pcl/CollisionDetector jsk_pcl/ColorBasedRegionGrowingSegmentation jsk_pcl/ColorHistogram jsk_pcl/ColorHistogramClassifier jsk_pcl/ColorHistogramFilter jsk_pcl/ColorHistogramMatcher jsk_pcl/ColorizeDistanceFromPlane jsk_pcl/ColorizeHeight2DMapping jsk_pcl/ColorizeMapRandomForest jsk_pcl/ColorizeRandomForest jsk_pcl/ConvexConnectedVoxels jsk_pcl/DelayPointCloud jsk_pcl/DepthCalibration jsk_pcl/DepthImageCreator jsk_pcl/DepthImageError jsk_pcl/EdgeDepthRefinement jsk_pcl/EdgebasedCubeFinder jsk_pcl/EnvironmentPlaneModeling jsk_pcl/EuclideanClustering jsk_pcl/ExtractCuboidParticlesTopN jsk_pcl/ExtractIndices jsk_pcl/FeatureRegistration jsk_pcl/FindObjectOnPlane jsk_pcl/FisheyeSpherePublisher jsk_pcl/FuseDepthImages jsk_pcl/FuseRGBImages jsk_pcl/GridSampler jsk_pcl/HSIColorFilter jsk_pcl/HandleEstimator jsk_pcl/HeightmapConverter jsk_pcl/HeightmapMorphologicalFiltering jsk_pcl/HeightmapTimeAccumulation jsk_pcl/HeightmapToPointCloud jsk_pcl/HintedHandleEstimator jsk_pcl/HintedPlaneDetector jsk_pcl/HintedStickFinder jsk_pcl/ICPRegistration jsk_pcl/ImageRotateNodelet jsk_pcl/IncrementalModelRegistration jsk_pcl/InteractiveCuboidLikelihood jsk_pcl/IntermittentImageAnnotator jsk_pcl/JointStateStaticFilter jsk_pcl/KeypointsPublisher jsk_pcl/Kinfu jsk_pcl/LINEMODDetector jsk_pcl/LINEMODTrainer jsk_pcl/LineSegmentCollector jsk_pcl/LineSegmentDetector jsk_pcl/MaskImageClusterFilter jsk_pcl/MaskImageFilter jsk_pcl/MaskImageToDepthConsideredMaskImage jsk_pcl/MaskImageToPointIndices jsk_pcl/MovingLeastSquareSmoothing jsk_pcl/MultiPlaneExtraction jsk_pcl/MultiPlaneSACSegmentation jsk_pcl/NormalConcatenater jsk_pcl/NormalDirectionFilter jsk_pcl/NormalEstimationIntegralImage jsk_pcl/NormalEstimationOMP jsk_pcl/NormalFlipToFrame jsk_pcl/OctomapServerContact jsk_pcl/OctreeChangePublisher jsk_pcl/OctreeVoxelGrid jsk_pcl/OrganizedEdgeDetector jsk_pcl/OrganizedMultiPlaneSegmentation jsk_pcl/OrganizedPassThrough jsk_pcl/OrganizedPointCloudToPointIndices jsk_pcl/PCDReaderWithPose jsk_pcl/PPFRegistration jsk_pcl/ParallelEdgeFinder jsk_pcl/ParticleFilterTracking jsk_pcl/PeopleDetection jsk_pcl/PlanarPointCloudSimulator jsk_pcl/PlaneConcatenator jsk_pcl/PlaneReasoner jsk_pcl/PlaneRejector jsk_pcl/PlaneSupportedCuboidEstimator jsk_pcl/PointCloudLocalization jsk_pcl/PointCloudToClusterPointIndices jsk_pcl/PointCloudToSTL jsk_pcl/PointIndicesToMaskImage jsk_pcl/PointcloudDatabaseServer jsk_pcl/PointcloudScreenpoint jsk_pcl/PolygonAppender jsk_pcl/PolygonArrayAngleLikelihood jsk_pcl/PolygonArrayAreaLikelihood jsk_pcl/PolygonArrayDistanceLikelihood jsk_pcl/PolygonArrayFootAngleLikelihood jsk_pcl/PolygonArrayTransformer jsk_pcl/PolygonArrayUnwrapper jsk_pcl/PolygonArrayWrapper jsk_pcl/PolygonFlipper jsk_pcl/PolygonMagnifier jsk_pcl/PolygonPointsSampler jsk_pcl/PoseWithCovarianceStampedToGaussianPointCloud jsk_pcl/PrimitiveShapeClassifier jsk_pcl/RGBColorFilter jsk_pcl/ROIClipper jsk_pcl/RearrangeBoundingBox jsk_pcl/RegionGrowingMultiplePlaneSegmentation jsk_pcl/RegionGrowingSegmentation jsk_pcl/ResizePointsPublisher jsk_pcl/SelectedClusterPublisher jsk_pcl/Snapit jsk_pcl/SphericalPointCloudSimulator jsk_pcl/StaticPolygonArrayPublisher jsk_pcl/SupervoxelSegmentation jsk_pcl/TargetAdaptiveTracking jsk_pcl/TfTransformBoundingBox jsk_pcl/TfTransformBoundingBoxArray jsk_pcl/TfTransformCloud jsk_pcl/TiltLaserListener jsk_pcl/TorusFinder jsk_pcl/TransformPointcloudInBoundingBox jsk_pcl/VoxelGridDownsampleDecoder jsk_pcl/VoxelGridDownsampleManager jsk_pcl/VoxelGridLargeScale jsk_pcl_utils/AddPointIndices jsk_pcl_utils/BoundingBoxArrayToBoundingBox jsk_pcl_utils/CentroidPublisher jsk_pcl_utils/CloudOnPlane jsk_pcl_utils/ClusterPointIndicesToPointIndices jsk_pcl_utils/ColorizeDistanceFromPlane jsk_pcl_utils/ColorizeHeight2DMapping jsk_pcl_utils/DelayPointCloud jsk_pcl_utils/DepthImageError jsk_pcl_utils/LabelToClusterPointIndices jsk_pcl_utils/MarkerArrayVoxelToPointCloud jsk_pcl_utils/MaskImageToDepthConsideredMaskImage jsk_pcl_utils/MaskImageToPointIndices jsk_pcl_utils/NormalConcatenater jsk_pcl_utils/NormalFlipToFrame jsk_pcl_utils/PCDReaderWithPose jsk_pcl_utils/PlanarPointCloudSimulator jsk_pcl_utils/PlaneConcatenator jsk_pcl_utils/PlaneReasoner jsk_pcl_utils/PlaneRejector jsk_pcl_utils/PointCloudRelativeFromPoseStamped jsk_pcl_utils/PointCloudToClusterPointIndices jsk_pcl_utils/PointCloudToMaskImage jsk_pcl_utils/PointCloudToPCD jsk_pcl_utils/PointCloudToPointIndices jsk_pcl_utils/PointCloudToSTL jsk_pcl_utils/PointCloudXYZRGBToXYZ jsk_pcl_utils/PointCloudXYZToXYZRGB jsk_pcl_utils/PointIndicesToClusterPointIndices jsk_pcl_utils/PointIndicesToMaskImage jsk_pcl_utils/PolygonAppender jsk_pcl_utils/PolygonArrayAngleLikelihood jsk_pcl_utils/PolygonArrayAreaLikelihood jsk_pcl_utils/PolygonArrayDistanceLikelihood jsk_pcl_utils/PolygonArrayFootAngleLikelihood jsk_pcl_utils/PolygonArrayLikelihoodFilter jsk_pcl_utils/PolygonArrayTransformer jsk_pcl_utils/PolygonArrayUnwrapper jsk_pcl_utils/PolygonArrayWrapper jsk_pcl_utils/PolygonFlipper jsk_pcl_utils/PolygonMagnifier jsk_pcl_utils/PolygonPointsSampler jsk_pcl_utils/PoseWithCovarianceStampedToGaussianPointCloud jsk_pcl_utils/SphericalPointCloudSimulator jsk_pcl_utils/StaticPolygonArrayPublisher jsk_pcl_utils/SubtractPointIndices jsk_pcl_utils/TfTransformBoundingBox jsk_pcl_utils/TfTransformBoundingBoxArray jsk_pcl_utils/TfTransformCloud jsk_pcl_utils/TransformPointcloudInBoundingBox jsk_perception/AddMaskImage jsk_perception/ApplyMaskImage jsk_perception/BackgroundSubstraction jsk_perception/Bing jsk_perception/BlackHat jsk_perception/BlobDetector jsk_perception/BoundingBoxToRect jsk_perception/BoundingObjectMaskImage jsk_perception/BoundingRectMaskImage jsk_perception/Closing jsk_perception/ColorHistogram jsk_perception/ColorHistogramLabelMatch jsk_perception/ColorizeFloatImage jsk_perception/ColorizeLabels jsk_perception/ConcaveHullMaskImage jsk_perception/ConsensusTracking jsk_perception/ContourFinder jsk_perception/ConvexHullMaskImage jsk_perception/DilateMaskImage jsk_perception/DrawRects jsk_perception/EdgeDetector jsk_perception/ErodeMaskImage jsk_perception/FilterMaskImageWithSize jsk_perception/FisheyeToPanorama jsk_perception/FlowVelocityThresholding jsk_perception/GaussianBlur jsk_perception/GrabCut jsk_perception/GridLabel jsk_perception/HSVDecomposer jsk_perception/HoughCircleDetector jsk_perception/HoughLineDetector jsk_perception/KMeans jsk_perception/LabDecomposer jsk_perception/LabelToMaskImage jsk_perception/MaskImageGenerator jsk_perception/MaskImageToROI jsk_perception/MaskImageToRect jsk_perception/MorphologicalGradient jsk_perception/MultiplyMaskImage jsk_perception/Opening jsk_perception/OverlayImageColorOnMono jsk_perception/PolygonArrayColorHistogram jsk_perception/PolygonArrayColorLikelihood jsk_perception/PolygonArrayToLabelImage jsk_perception/PolygonToMaskImage jsk_perception/ProjectImagePoint jsk_perception/RGBDecomposer jsk_perception/ROIToMaskImage jsk_perception/ROIToRect jsk_perception/RectArrayActualSizeFilter jsk_perception/RectArrayToDensityImage jsk_perception/RectToMaskImage jsk_perception/RectToROI jsk_perception/RobotToMaskImage jsk_perception/SLICSuperPixels jsk_perception/SaliencyMapGenerator jsk_perception/SingleChannelHistogram jsk_perception/Skeletonization jsk_perception/SlidingWindowObjectDetector jsk_perception/SnakeSegmentation jsk_perception/SparseImageDecoder jsk_perception/SparseImageEncoder jsk_perception/TabletopColorDifferenceLikelihood jsk_perception/TopHat jsk_perception/UnapplyMaskImage jsk_perception/YCCDecomposer jsk_topic_tools/Block jsk_topic_tools/DeprecatedRelay jsk_topic_tools/HzMeasure jsk_topic_tools/LightweightThrottle jsk_topic_tools/MUX jsk_topic_tools/Passthrough jsk_topic_tools/Relay jsk_topic_tools/Snapshot jsk_topic_tools/StealthRelay jsk_topic_tools/StringRelay jsk_topic_tools/VitalCheckerNodelet jsk_topic_tools_test/LogUtils laser_proc/LaserProcNodelet lk_flow/lk_flow nodelet_tutorial_math/Plus octomap_server/OctomapServerNodelet openni2_camera/OpenNI2DriverNodelet openni_camera/driver pcl/BoundaryEstimation pcl/FPFHEstimation pcl/FPFHEstimationOMP pcl/MomentInvariantsEstimation pcl/NormalEstimationOMP people_detect/people_detect phase_corr/phase_corr pointcloud_to_laserscan/pointcloud_to_laserscan_nodelet resized_image_transport/ImageResizer resized_image_transport/LogPolar rgb_color_filter/rgb_color_filter segment_objects/segment_objects simple_compressed_example/simple_compressed_example simple_example/simple_example simple_flow/simple_flow smoothing/smoothing stereo_image_proc/disparity stereo_image_proc/point_cloud2 threshold/threshold watershed_segmentation/watershed_segmentation
```

The original problem is fixed in https://github.com/ros-perception/perception_pcl/pull/132, but it is not still released on indigo.

```bash
furushchev@ease:~$ cat /etc/apt/sources.list.d/ros-latest.list
deb http://packages.ros.org/ros-shadow-fixed/ubuntu trusty main
furushchev@ease:~$ rosversion pcl_ros
1.2.7
```

but the latest version of `pcl_ros` is now `1.5.3`.

**Comment by furushchev** [comment]
Updated to use fixed environment for each robot

**Comment by furushchev** [comment]
https://github.com/jsk-ros-pkg/jsk_robot/issues/902 blocks this test.

**Comment by furushchev** [comment]
Restarted and travis passed this time.
@k-okada  Please merge if there is no problem.

**Pull request merged**
