### PR TITLE
[WIP] microwave demo

### PR DESCRIPTION
**Pull request by takayuki5168**

### CODE REVIEW

**Comment by takayuki5168** [comment]
This is a PR of demo of PR2 using a microwave.
The code has a euslisp interface that enables PR2 to go to microwave, open the door, close the door, put the object in it, push heat button and start button... etc.

Anne also used this code when her final demo of baking a cake.

Now I will refactor this code and also make a PR of baking a cake.

**Comment by Kanazawanaoaki** [comment]
I think this pull request will be a reference for @samejima00.

**Comment by knorth55** [comment]
@Kanazawanaoaki can you add your own changes on this PR and make another PR?

**Comment by takayuki5168** [comment]
I don't do maintenance on this PR anymore, so I close.
If this PR should still be opened, please make another PR.

**Pull request closed without merging**
