### PR TITLE
add build dependencies for catkin build; fix typo install

### PR DESCRIPTION
**Pull request by furushchev**

### CODE REVIEW

**Comment by garaemon** [comment]
SnapMapICP is required

```
[detect_cans_in_fridge_201202] CMake Error at /opt/ros/hydro/share/catkin/cmake/catkinConfig.cmake:75 (find_package): 
[detect_cans_in_fridge_201202]   Could not find a configuration file for package snap_map_icp. 
[detect_cans_in_fridge_201202]  
[detect_cans_in_fridge_201202]   Set snap_map_icp_DIR to the directory containing a CMake configuration file 
[detect_cans_in_fridge_201202]   for snap_map_icp.  The file will have one of the following names: 
[detect_cans_in_fridge_201202]  
[detect_cans_in_fridge_201202]     snap_map_icpConfig.cmake 
[detect_cans_in_fridge_201202]     snap_map_icp-config.cmake 

```

**Comment by garaemon** [comment]
https://github.com/code-iai/snap_map_icp

**Comment by furushchev** [comment]
@garaemon thanks for advice!

**Comment by furushchev** [comment]
yay! travis passed!

**Comment by garaemon** [comment]
:+1:

**Pull request merged**
