### PR TITLE
[drc_task_common] Estimate collision link pairs according to the robot model and link list

### PR DESCRIPTION
**Pull request by garaemon**
* Estimate pairs of collision links according to the given link list and number of pairs

N=1
screenshot from 2015-12-15 20 37 38

N=5
screenshot from 2015-12-15 20 37 55

N=50
screenshot from 2015-12-15 20 38 24

* link-pair class and it is objectable like natto-viewer

screenshot from 2015-12-15 19 38 54
screenshot from 2015-12-15 19 38 41

### CODE REVIEW

**Comment by snozawa** [comment]
Is this same as https://github.com/euslisp/jskeus/blob/master/irteus/irtmodel.l#L1214?

**Comment by garaemon** [comment]
It decide collision pairs according allowed number of pairs and initial distance.
A litle bit different

**Comment by garaemon** [comment]
The algorithm is:

Given: 

* N .. number of collision pairs
* L .. link list

1. move robot mode lto "initial pose"
2. compute distances between links
3. Use top-N link pairs which are shorter distance links (link pairs should be included in L of course)

**Comment by snozawa** [comment]
I see.
Which program use this?

> It decide collision pairs according allowed number of pairs and initial distance.

I could not fully understand why initial distance or max number is important to determine collision pairs.

**Pull request closed without merging**
