### PR TITLE
[detect_cans_in_fridge_201202] fix: wrong arg name at some launch files

### PR DESCRIPTION
**Pull request by furushchev**
current launch files does not work without this fix.

### CODE REVIEW

**Comment by furushchev** [comment]
@h-kamada Please review.

**Comment by furushchev** [comment]
@h-kamada kindly ping to author.

**Comment by furushchev** [comment]
@h-kamada Any comment?

**Comment by h-kamada** [comment]
Sorry for late response.
Please merge!

**Comment by furushchev** [comment]
You mean the change in this pull request is ok for you?

**Comment by k-okada** [comment]
@h-kamada, please check with real robot ;-)

--
◉ Kei Okada


2016-10-25 22:24 GMT+09:00 Furushchev <notifications@github.com>:

**Comment by h-kamada** [comment]
As @furushchev mensioned, `visualize_fridge` arg name was wrong. Please merge!

**Pull request merged**
